### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by pranusarna94** [skpm/skpm#102]
Every time I install a third party node module like, say, webfonts-generator and require it in the main script file like this:

`import webfontsGenerator from 'webfonts-generator'`

**I get this error:**

`Error while building ./my-command.js
./node_modules/handlebars/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/pranusarna/development/sketch/iconator/node_modules/handlebars/lib'
resolve 'fs' in '/Users/pranusarna/development/sketch/iconator/node_modules/handlebars/lib'
  Parsed request is a module
  using description file: /Users/pranusarna/development/sketch/iconator/node_modules/handlebars/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/pranusarna/development/sketch/iconator/node_modules/handlebars/package.json (relative path: ./lib)
    resolve as module
      /Users/pranusarna/development/sketch/iconator/node_modules/handlebars/lib/node_modules doesn't exist or is not a directory`

any idea on what i am doing wrong?

**Comment by mathieudutour** [comment]
I don't think it's _every time_. It's when you try to use a package that uses some nodejs module (`fs` here)

**Comment by pranusarna94** [comment]
Oh got it. Any way how I can make such a module work? Sorry but I am a newbie to sketch plugging Dev

**Comment by mathieudutour** [comment]
that module in particular is going to be pretty hard. A rule of thumb is that if the module can't run in the browser, it probably won't run in Sketch
