### ISSUE TITLE
TypeError: Function is not a function. (In 'Function('return this')', 'Function' is an instance of MOBoxedObject)

### ISSUE THREAD

**Issue by nikogu** [skpm/skpm#103]
sketch: 48 is `ok`

error in: 
- sketch: 47.x
- osx: 10.13.2 
- xcode: 9.2

in builded code: 
```js
/***/ (function(module, exports) {

// https://github.com/zloirock/core-js/issues/86#issuecomment-115759028
var global = module.exports = typeof window != 'undefined' && window.Math == Math
  ? window : typeof self != 'undefined' && self.Math == Math ? self
  // eslint-disable-next-line no-new-func
  : Function('return this')();
if (typeof __g == 'number') __g = global; // eslint-disable-line no-undef
```

![image](https://user-images.githubusercontent.com/1179603/34337149-10c2ff9e-e998-11e7-98d2-e3ee8b2958d1.png)

suggest change to `(function(){return this})()`

it's skpm's issue ? i am using `skpm build`, the `index.js` has such code.

**Comment by mathieudutour** [comment]
it's not a skpm issue. macOS 10.13 brings a new obj-c class called `Function`. CocoaScript (the bridge between obj-c and js) didn't take it into account so any code using `Function()` though that it was calling the obj-c class.

I fixed it on Sketch 48.
