### ISSUE TITLE
Every time saving (building) the manifest.json file, I get an error

### ISSUE THREAD

**Issue by pixelcommerce** [skpm/skpm#104]
This error keeps showing up, even though my manifest.json file is following exactly what's on sketch's developer site:

(node:9438) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: compilers.map is not a function

This error is non-descriptive and I'm not sure how to fix this?

**Comment by mathieudutour** [comment]
I think it's when you are watching and the `manifest.json` changes. What version of `@skpm/builder` are you using?

**Comment by pixelcommerce** [comment]
Sorry for the late reply: it's 1.0.12

**Comment by eli-crow** [comment]
I am running into the same issue. version listed in `package.json` is `"@skpm/builder": "^0.2.0"`

**Comment by mathieudutour** [comment]
Found it! Should be fixed in `@skpm/builder@v0.3.0`
