### ISSUE TITLE
Upon creating updates to my Sketch Plugin, no updates go through

### ISSUE THREAD

**Issue by pixelcommerce** [skpm/skpm#108]
As I update the files in my sketch plugin, no updates occur. When I update the manifest.json file, the information isn't updated. 

When I change the js file, nothing gets executed: 

```
{
  "identifier" : "unique.line.testing",
  "version" : "1.0",
  "description" : "This description for the tool",
  "name" : "Tool Name",
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "commands": [
    {
        "script" : "currentFile.js",
        "handler": "handlerForFunction",
        "name" : "handler for function",
        "indentifier" : "handlerforfunction"
    }
  ],
  "menu": {
    "items": [
      "handlerforfunction"
    ]
  }
}
```

For instance, the menu isn't showing in the top of the nav in the plugins menu. I've run `npm run watch`. Anyone know what seems to be the problem? Maybe I should just do this all manually since this is just causing more problems?

**Comment by mathieudutour** [comment]
do you have a repo where I could repro the issue?

**Comment by pixelcommerce** [comment]
I do not, but I'm realizing that when ever compiling my manifest.json, there aren't errors showing me what the issue was. So what I did was I just copied and pasted from an example (it worked), then modified it to what I needed. Oh well...

**Comment by pixelcommerce** [comment]
I think I found the issue... the "compatibleVersion" didn't have quotations for 3... I think that's what was causing it to not show anymore. This comes back to my thinking of error handling and letting us know what errors have occurred so we can fix them.

**Comment by mathieudutour** [comment]
Well that's not a skpm issue, the `manifest.json` is a Sketch thing and if sketch doesn't return an issue, skpm can't possibly know about it

**Comment by pixelcommerce** [comment]
Well then I'm at a loss! Anyway, thanks for the help.
