### ISSUE TITLE
'resourceLoader' produces incorrect public path during Windows builds

### ISSUE THREAD

**Issue by romansp** [skpm/skpm#111]
I know, building Sketch plugins on Windows doesn't seem like a good idea 😃, because in the end plugin will run on Mac anyway, but I am currently required to setup plugin's CI build pipeline that's is a part of some other high-level CI that runs on only Windows. 

Currently builds are passing successfully, however I stumbled upon an issue in paths produced by `resourceLoader`. 

https://github.com/skpm/skpm/blob/98deef81339404298fe6a93473ecef43cc2c8b03/packages/builder/src/utils/resourceLoader.js#L11-L18

On a Windows, `path.join` in `outputPath` produces a path joined with backslash `\\`. Thus, split in `publicPath` will result in `undefined`.

Fix will be to explicitly specifiy in `outputPath` to use [`posix` path join](https://nodejs.org/api/path.html#path_path_posix). 

Will you be interested if I provide a PR? What's your view on supporting Windows builds in general?

**Comment by mathieudutour** [comment]
never thought it would be a use case haha

Happy to accept PR to fix stuff for windows but I won't fix them myself, don't have any windows machine ;)
