### ISSUE TITLE
getting error when using sketch-polyfill-console

### ISSUE THREAD

**Issue by DanielRuf** [skpm/skpm#118]
```
error Error while building ./index.js
./node_modules/sketch-utils/to-array.js
Module parse failed: Unexpected token (7:23)
You may need an appropriate loader to handle this file type.
|   var arr = []
|   for (var j = 0; j < (object || []).length; j += 1) {
|     arr.push(object[j]))
|   }
|   return arr
 @ ./node_modules/sketch-utils/index.js 3:25-46
 @ ./node_modules/sketch-polyfill-console/lib/index.js
 @ ./node_modules/promise-polyfill/lib/index.js
 @ ./node_modules/sketch-polyfill-fetch/lib/index.js
```

**Comment by mathieudutour** [comment]
it's only when using `console.log`. It's already fixed but I don't have my phone right now so can't publish the new version (2FA). Will do so as soon as I get it back

**Comment by DanielRuf** [comment]
> it's only when using console.log

Not sure what you mean but I did not use `console.log` afaik.
Do you mean https://github.com/skpm/sketch-utils/commit/d19f0962c61755dbe924bb3b8a27d40c7600cf5a#diff-f170df27fa7f31a6ea58c1399c6d40df?

**Comment by mathieudutour** [comment]
yes sorry. In the meantime you can replace the `to-array.js` file by this one: https://github.com/skpm/sketch-utils/blob/master/to-array.js

**Comment by mathieudutour** [comment]
should be good now

**Comment by DanielRuf** [comment]
Ok, I'll try to test again this week. Thanks for taking care of it and fixing this.
