### ISSUE TITLE
compatibility with latest Sketch 49 Javascript API

### ISSUE THREAD

**Issue by tijmenvangurp** [skpm/skpm#124]
Maybe I am doing something wrong but I expected that this would work:

`
export default function(context) {
  var sketch = require('sketch')
  context.document.showMessage("It's alive 🙌")
}
`

Base on http://developer.sketchapp.com/reference/api/#installation 

It throws the following error:
Module not found: Error: Can't resolve 'sketch' in ' /path/to/plugin/my-comman.js

And in the code, it shows this:
`
 var sketch = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"sketch\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
`
I guess that normally you would want to install it as a module but this is kind of an exception according to sketch. 

The API comes bundled inside Sketch, so no installation is required. You access it by calling the global require function.

**Comment by mathieudutour** [comment]
Hum works fine here. What version of `@skpm/builder` are you using?

**Comment by tijmenvangurp** [comment]
Hey, I am on skpm 1.0.13,
npm version: 5.6.0 
Node version v6.11.1

Am I doing something wrong then?
You are able to use the new sketch API by calling require('sketch') ?

**Comment by tijmenvangurp** [comment]
It says 
"@skpm/builder": "^0.1.3",
So not 0.4 or above. Can you help me with this? what is the issue here?

**Comment by mathieudutour** [comment]
Well it’s just an old version. 

To update, run `npm install @skpm/builder@0.4`
