### ISSUE TITLE
Recommendation for using skpm in larger build process

### ISSUE THREAD

**Issue by cameronmcefee** [skpm/skpm#130]
Hello!

I'm using skpm in a project that uses a shared React app codebase that powers the UI for extensions in Sketch, Photoshop, and Illustrator. Because of this setup, there are a few different steps involved in compiling each extension (so I can't use skpm by itself). What's the best practice for using skpm in this world? My current thought is:

- Compile the React app with Webpack to a location where skpm can use it.
- Run skpm build

Is this right, or is there a way to work skpm into the webpack process itself? I don't need working examples, I'm just curious conceptually about the best way to do it

**Comment by mathieudutour** [comment]
there are some webpack plugin to run a command after the build (so it works with the watch mode as well), I would go with that I guess

**Comment by cameronmcefee** [comment]
:+1: thanks, I'll look into that.
