### ISSUE TITLE
skpm builder throw error when use module webview with vue

### ISSUE THREAD

**Issue by nichenqin** [skpm/skpm#131]
I use `vue` to render interface in webview and config `webpack.skpm.config.js` to add a `vue-loader` and so far so good.
But once I add an `image` tag and import a picture, webpack notice that I have to config another loader to handler image file.
Then I use the `file-loader` module but the image file are built into the `plugin.sketchplugn/Contents/Resources` folder, not `plugin.sketchplugn/Contents/Resources/_webpack_resources` and the  url goes wrong(the image never show)

I browse the `@skpm/builder/lib/resourceLoader.js` file and find there is some config to bundle the assets to the `_webpack_resources` but unlukily the code throw error before it can use the loader.

Can you figure out a way that I can bundle the assets file to the `_webpack_resources` folder? Thanks!

**Comment by mathieudutour** [comment]
I'm not sure I understand but I think you need to specify the `outputPath` in the config of your `file-loader`

**Comment by nichenqin** [comment]
I find you use the `context.plugin.urlForResourceNamed` to specify the path, maybe I can try `__dirname`, that's my miss, thanks
