### ISSUE TITLE
Define user webpack config

### ISSUE THREAD

**Issue by nichenqin** [skpm/skpm#132]
Hi, I have an issue about the custom webpack config defined in `webpack.skpm.config.js` which  currently exports a function.

Can you consider use some module like `webpack-merge` to ensure we can export an object from our custom config so that I don't need to guess which config property is defined or not in `skpm/builder`.And I feel it's a little bit weird to mutate an object through parameter.

**Comment by mathieudutour** [comment]
yes I'm actually using that for the new version of @skpm/builder (which will use webpack 4 and babel 7)
