### ISSUE TITLE
cannot work properly if plugin name contains space

### ISSUE THREAD

**Issue by PeachScript** [skpm/skpm#133]
## Version

1.0.14

## What is expected?

The command `skpm --run` work properly.

## What is actually happening?

`copyAsset` will throw error.

## How to reproduce this problem?

Just set plugin name like `Sketch Plugin` and execute `skpm --run`, it looks like caused by no space escaped for system command, for example, we should use `cp foo.bar ./Sketch\ Plugin/foo.bar` rather than `cp foo.bar ./Sketch Plugin/foo.bar`.

Almost forgot, thank you for this great tool :D

**Comment by mathieudutour** [comment]
Good catch, thanks
