### ISSUE TITLE
Plugin does not update

### ISSUE THREAD

**Issue by lukasoppermann** [skpm/skpm#137]
Hey,

I can't get the plugin to update in sketch. The initial version from `skpm create` is there, but now that I changed something, when I run `npm run build` Sketch does not reflect the changes.

I don't get errors and it says `success Plugin built`

My manifest.json (only thing I touched so far);

```json
{
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "name": "Browser Preview",
  "description": "Quickly preview an artboard in your browser.",
  "author": "Lukas Oppermann",
  "icon": "icon.png",
  "commands": [
    {
      "name": "Preview Artboard",
      "identifier": "browser-preview",
      "script": "./my-command.js"
    },
    {
      "name": "Settings",
      "identifier": "browser-preview-settings",
      "script": "./my-command.js"
    }
  ],
  "menu": {
    "title": "🔍 Browser Preview",
    "items": [
      "browser-preview",
      "browser-preview-settings"
    ]
  }
}

```

Any idea? Can I somehow provide more information?

**Comment by mathieudutour** [comment]
I'm guessing you have a webview or something? In that case you need to restart sketch because it keeps your script in memory

See https://github.com/BohemianCoding/SketchAPI/pull/165/files

**Comment by robintindale** [comment]
Another useful thing to mention is the `Always reload scripts before running` section on https://developer.sketchapp.com/guides/preferences/

Running `defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES` in the Terminal asks Sketch to reload the plugin script every time a command is run (instead of caching it)

**Comment by allesklarbeidir** [comment]
> Another useful thing to mention is the `Always reload scripts before running` section on https://developer.sketchapp.com/guides/preferences/
> 
> Running `defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES` in the Terminal asks Sketch to reload the plugin script every time a command is run (instead of caching it)

Despite having this option enabled, make sure to always call `fiber.cleanup();` if you're using async
functions (see [https://developer.sketch.com/reference/api/#async](https://developer.sketch.com/reference/api/#async)).

I missed one `fiber.cleanup();` call and that's what made sketch not reload my plugin after rebuilding with skpm.
