### ISSUE TITLE
Different manifest as parameter.

### ISSUE THREAD

**Issue by damianprzygodzki** [skpm/skpm#140]
As i understood, the start point of build is manifest - there we define what we want to build. It would be great to have ability to give skpm as a parameter optional manifest (if we want to i.e. build another version of our plugin, and exchanging package.json property is a bit hussle when we want make some automation)

**Comment by mathieudutour** [comment]
Interesting. Happy to accept a PR for it.

An easy way to do it would to change https://github.com/skpm/skpm/blob/master/packages/utils/skpm-config.js:

```
...
module.exports = function getSkpmConfig(packageJSON) {
args = args || {}
...
  manifest: process.env.SKPM_MANIFEST || skpmConfig.manifest || packageJSON.manifest,
...
}
...
```

and then you could do `SKPM_MANIFEST=path/to/manifest.json skpm-build`

**Comment by damianprzygodzki** [comment]
@mathieudutour wdyt about that #141 ?
