### ISSUE TITLE
How to use master version of package?

### ISSUE THREAD

**Issue by damianprzygodzki** [skpm/skpm#143]
After my PR #141 i've tried to somehow use it in my project. But i can't find a way to make it works.

1) I can't install globally by `npm i -g github.com:skpm/skpm.git#master` - it didn't see package.json. 
>Could not install from "github.com:skpm/skpm.git" as it does not contain a package.json file.

[And than, how i even should define it as dependency to private scoped package?]

2)  I can't install it as dev dependency - there is missing package name: 
> Can't install github:skpm/skpm#f09bfdb003ffd2b3e8b6a355bd50f08ef1caa2ef: Missing package name

3) I can't install scoped package `@skpm\builder` by  #`git@github.com:skpm/skpm/packages/builder`. It is not documented by npm - i assume that is impossible.

Node v9.11.1
Npm v5.6.0

**Comment by mathieudutour** [comment]
I don't think that's possible indeed for multiple reasons:
- multiple packages in the repo
- need to compile the files

**Comment by damianprzygodzki** [comment]
Don't want to hassle much, but its blocker for our project :) If there is any way to help you with tasks related to release let me know :)

**Comment by mathieudutour** [comment]
it's already released :)

**Comment by damianprzygodzki** [comment]
Great. It is working perfectly! Thank you
