### ISSUE TITLE
skpm create: Error: Exited with status 1

### ISSUE THREAD

**Issue by sambernhardt** [skpm/skpm#145]
I can't get `skpm create` to run successfully. Every time during "Installing dependencies" it errors out with the message: `Error: Exited with status 1`

I've already tried reinstalling skpm and also when running npm install in the directory, it doesn't error out. Any thoughts?

My npm logs are below.

[2018-04-12T05_16_39_818Z-debug.log](https://github.com/skpm/skpm/files/1901404/2018-04-12T05_16_39_818Z-debug.log)
[2018-04-12T05_16_39_608Z-debug.log](https://github.com/skpm/skpm/files/1901405/2018-04-12T05_16_39_608Z-debug.log)

**Comment by mathieudutour** [comment]
Can you try running `npm run postinstall` in the directory?

**Comment by sambernhardt** [comment]
Yep! The following was logged:

[2018-04-12T05_51_49_004Z-debug.log](https://github.com/skpm/skpm/files/1901478/2018-04-12T05_51_49_004Z-debug.log)
[2018-04-12T05_51_48_968Z-debug.log](https://github.com/skpm/skpm/files/1901480/2018-04-12T05_51_48_968Z-debug.log)

**Comment by mathieudutour** [comment]
And no explanation as to why it failed was logged in the terminal?

Could you try running `./node_modules/.bin/skpm-link`? I have the feeling that it is one failing

**Comment by sambernhardt** [comment]
When I tried `npm run postinstall`, the following was returned in the terminal:

```
> my-project@0.1.0 postinstall /Users/Samuel/Dev/SketchPlugins/my-project
> npm run build && skpm-link


> my-project@0.1.0 build /Users/Samuel/Dev/SketchPlugins/my-project
> skpm-build

[1/3] 🖨  Copied src/manifest.json in 4ms
error Error while copying assets/icon.png
TypeError: _fs2.default.copyFile is not a function
    at /Users/Samuel/Dev/SketchPlugins/my-project/node_modules/@skpm/builder/lib/build.js:100:20
    at /Users/Samuel/Dev/SketchPlugins/my-project/node_modules/@skpm/builder/lib/build.js:99:12
    at next (native)
    at step (/Users/Samuel/Dev/SketchPlugins/my-project/node_modules/@skpm/builder/lib/build.js:276:191)
    at /Users/Samuel/Dev/SketchPlugins/my-project/node_modules/@skpm/builder/lib/build.js:276:361
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 build: `skpm-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Samuel/.npm/_logs/2018-04-12T05_51_48_968Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 postinstall: `npm run build && skpm-link`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Samuel/.npm/_logs/2018-04-12T05_51_49_004Z-debug.log
```

I'll give `./node_modules/.bin/skpm-link` a try. Thanks for your help thus far!

**Comment by sambernhardt** [comment]
`./node_modules/.bin/skpm-link` returned :

```
[1/1] 🔗  Symlinking the plugin my-project...
success Plugin my-project symlinked
my-project - 0.1.0
The Sketch developer mode is not enabled (http://developer.sketchapp.com/introduction/preferences/#always-reload-scripts-before-running).
Do you want to enable it? (y/N) y
success Sketch developer mode enabled

warning Starting with Sketch 45, you may need to restart Sketch for your plugin to appear in the "Plugins" menu
```

**Comment by mathieudutour** [comment]
Ah there it is! I was wrong, it’s because of the build. Can you make sure that your NodeJS version is >= 8.5?

**Comment by mathieudutour** [comment]
I’ll add a warning if `copyFile` doesn’t exist to make sure people have a recent enough node version

**Comment by sambernhardt** [comment]
Ahh gotcha! I've updated my NodeJS and it's all working fine now. I had a small issue where after I updated Node, my packages couldn't be found – but I resolved this with the instructions on this site: https://askubuntu.com/questions/250971/no-such-file-or-directory-error-while-using-npm

Thanks again!
