### ISSUE TITLE
@skpm/extract-loader does not support webpack4

### ISSUE THREAD

**Issue by nichenqin** [skpm/skpm#146]
The issue can refer to (https://github.com/peerigon/extract-loader/issues/32).

**Comment by mathieudutour** [comment]
just published `@skpm/extract-loader@2.0.1` which should solve this

**Comment by nichenqin** [comment]
@mathieudutour Hi mathieu, did you forget to build the code cause the module can't be resolved.

**Comment by mathieudutour** [comment]
Indeed, I forgot that it wasn't built automatically on publish. Fixed in 2.0.2
