### ISSUE TITLE
catching async uncaught errors

### ISSUE THREAD

**Issue by robintindale** [skpm/skpm#149]
this might be more of a api question (than skpm), but is it possible to catch all errors? i.e.
```
  try {
    setTimeout(function () {
      throw new Error('bye bye');
    }, 50);
  } catch (e) {
    log('oh dear :/');
  }
```
The `bye bye` gets printed (so there must be some global handler), but doesn't get caught

**Comment by mathieudutour** [comment]
Because you don’t catch the error in the timeout? I’m not sure I understand the question

**Comment by robintindale** [comment]
ah OK, I'm asking about the equivalent of `window.onerror` and `process.on('uncaughtException')` - a global handler for catching errors - in the sketch plugin env

**Comment by mathieudutour** [comment]
There is no equivalent because any async work gets a bit tricky. It would require some changes in CocoaScript. I actually have an issue open on the Sketch repo to look at it. I'll this one because there is no actionable on skpm

**Comment by robintindale** [comment]
ok thanks :) I tried playing with `NSSetUncaughtExceptionHandler` to no avail
