### ISSUE TITLE
Support globs for Resources folder

### ISSUE THREAD

**Issue by amin-nas** [skpm/skpm#15]
What's the best way to go about Resources folder? Run the build command and create the folder manually?

**Comment by mathieudutour** [comment]
I'm using the resources folder in [git-sketch-plugin](https://github.com/mathieudutour/git-sketch-plugin) (see the package.json). I haven't documented it because I'm not sure if it's the right approach yet.

**Comment by amin-nas** [comment]
I think it makes sense as long as I can do something like this:
```
"resources": [
    "Resources/*"
  ],
```

**Comment by mathieudutour** [comment]
Supporting globs is a good idea! I'll see if I have time to do it (or feel free to send a PR 😄 )

**Comment by alandickinson** [comment]
Hi Mathieu! Thanks for sharing the work you've been doing around sketch tooling. What's the correct way to load in static resources like html? I've set up a project similar to your example in sketch-module-web-view, but webpack is saying: "You may need an appropriate loader to handle this file type." I've tried with html-loader and raw-loader, but it keeps injecting js and assigning the html to a variable within the html file.

**Comment by mathieudutour** [comment]
there is a working example here: https://github.com/mathieudutour/git-sketch-plugin/blob/master/src/commands/Branches.js#L16

**Comment by alandickinson** [comment]
cool, I'll take a look. Thanks!

**Comment by mathieudutour** [comment]
fixed in 0.11.0
