### ISSUE TITLE
JSON parse error when publishing a plugin 

### ISSUE THREAD

**Issue by dynamite-ready** [skpm/skpm#153]
I'm currently trying to publish a plugin to the Sketch repo with:

`skpm publish minor`

The script appears to get to the very end of the process, but fails with:

`
⠼ Publishing the plugin on the official plugin directory
SyntaxError: Unexpected token ] in JSON at position 137575
`

The plugin works fine locally.
Any obvious reason for this error?

**Comment by ziven27** [comment]
I got the same problem like you

**Comment by mathieudutour** [comment]
the plugin directory was broken. Should be fine now
