### ISSUE TITLE
Project does not contain a handler function named: onRun

### ISSUE THREAD

**Issue by mateus** [skpm/skpm#155]
I recently updated the dependencies on my project to be:

```
"devDependencies": {
    "@skpm/builder": "^0.5.4",
    "@skpm/extract-loader": "^2.0.2",
    . . .
}
"dependencies": {
    "sketch-module-web-view": "^1.1.4"
}
```

But now I'm getting this error that I didn't have before. Would it be related to the updates?
```
Error in command Search in Polaris Script at path ...Contents/Sketch/plugin.js does not contain a handler function named: onRun.
```

My `plugin.js` only exports default a function but it seems to be looking for `onRun`.

```
export default function(context) {
  . . . 
}
```

cc @mathieudutour

**Comment by mathieudutour** [comment]
if you look at the compiled js, there should be a `that['onRun'] = exports.default` or something similar. 

- Do you run the plugin from the menu?
- what does your manifest.json look like?
- Do you have a repro available?

**Comment by mateus** [comment]
> Do you have a repro available?

https://github.com/Shopify/polaris-telescope/tree/master/src

I'll have a look at the other questions you've asked

**Comment by mateus** [comment]
> if you look at the compiled js, there should be a that['onRun'] = exports.default or something similar.

On `polaris-telescope.sketchplugin/Contents/Sketch/plugin.js` the last line is:
`that['onRun'] = __skpm_run.bind(this, 'default')`

**Comment by robintindale** [comment]
This is the same error message as seen http://sketchplugins.com/d/668-can-t-run-plugin-after-disabling-other-plugins/9 which is to do with running an action again which is already running, so check that your action is completing (and not leaving fibers / coscript keeparounds)

**Comment by mathieudutour** [comment]
Ah indeed, I forgot about that. Is it working on the [Sketch 50 beta](https://sketchapp.com/beta)? I can't find anything that looks broken otherwise
