### ISSUE TITLE
Changing build path in package.json will not properly create directories to link plugin

### ISSUE THREAD

**Issue by thecalvinchan** [skpm/skpm#165]
If i specify a nested build path inside my `package.json` file, it will not create the proper directories inside the Sketch app directory to symlink the plugin

i.e. 
```
{
  "skpm": {
    "name": "trade-flow-sketch-plugin",
    "manifest": "sketch/manifest.json",
    "main": "build/plugin.sketchplugin"
  }
}
```

```
[1/1] 🔗  Symlinking the plugin trade-flow-sketch-plugin...
error Error while symlinking the plugin trade-flow-sketch-plugin
{ Error: ENOENT: no such file or directory, symlink '/Users/calvinchan/airswap/trade-flow/build/plugin.sketchplugin' -> '/Users/calvinchan/Library/Application Support/com.bohemiancoding.sketch3/Plugins/trade-flow-sketch-plugin/build/plugin.sketchplugin'
```

If I remove the `build/` directory from package.json, it symlinks fine

**Comment by thecalvinchan** [comment]
yup, i get this error when i build the plugin from scratch

```
$ npm run sketch:build && skpm-link

> trade-flow@0.1.0 sketch:build /Users/calvinchan/airswap/trade-flow
> NODE_ENV='development' skpm-build

[1/2] 🖨  Copied sketch/manifest.json in 1ms
[2/2] 🔩  Built ./my-command.js in 1519ms
success Plugin built
[1/1] 🔗  Symlinking the plugin trade-flow-sketch-plugin...
error Error while symlinking the plugin trade-flow-sketch-plugin
```

**Comment by thecalvinchan** [comment]
so i think the issue is that I can specify a more specific path for `skpmConfig.main` (i.e. `build/plugin.sketchplugin`) and that will output the built plugin in that directory,

however, when linking, the linker uses `skpmConfig.name` to create the directory and attempts to link
via `join(pluginDirectory, skpmConfig.name, skpmConfig.main)`. If more specific path is specified in `skpmConfig.main`, then that will fail bc those directories are not created inside `pluginDirectory`

it is okay, if this is intended behavior, but I either propose to have more documentation on what those properties specify in the config, or strip all preceding directories in `skpmConfig.main` before linking. I can work on a PR for the latter if that is okay @mathieudutour

**Comment by mathieudutour** [comment]
oh indeed it's a bug. I guess it should be `join(pluginDirectory, skpmConfig.name, path.basename(skpmConfig.main))`
