### ISSUE TITLE
sketchPath in ~/.skpmrc not working

### ISSUE THREAD

**Issue by resting** [skpm/skpm#171]
I've added this to `~/.skpmrc`
```
sketchPath: /Applications/Sketch.app
```
But its still finding another copy stored else where.
Tried renaming that copy but running `npm run start` still points to it somehow.

**Comment by kara-todd** [comment]
I had this problem as well... 

For me installing [learna](https://lernajs.io/) (`npm install --global lerna`) and then running `npm install --global skpm` seemed to fix the issue.

**Comment by mathieudutour** [comment]
fixed in https://github.com/skpm/skpm/commit/b2a3204bf1e97ea2e06cf467eed779b99188b387

(you could also specify the path to the Sketch app with `skpm-build --watch --run --app=PATH/TO/APP.app`)
