### ISSUE TITLE
Tests cannot be generated in a loop

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [skpm/skpm#177]
Because of how the tests are loaded, generating tests based on an array of test cases does not work. Only the last test in the loop will run.

Example:
```js
testCases.forEach((testCase) => { 
  test(testCase, runTest(testCase))
});
```

**Comment by mathieudutour** [comment]
maybe your `testCase` are identical? the tests are stored in an object so if there is the same description, it will get overwritten. We should that but I want to understand if that's really it first?

**Comment by 10xLaCroixDrinker** [comment]
In the example above `testCases` is `['text', 'shape', 'layout']`.

**Comment by mathieudutour** [comment]
hum weird, I'll have a look
