### ISSUE TITLE
Can't find variable: require, in Sketch 48

### ISSUE THREAD

**Issue by tarunmangukiya** [skpm/skpm#178]
I've build the plugin package using newer version of sketch 50. But it's not working for some of the users having Sketch 48.

The error is as below:
```Exception: ReferenceError: Can't find variable: require```
on Line
```module.exports = require("sketch");```

Can anyone help me to resolve the issue?

**Comment by mathieudutour** [comment]
yeah the new API and `require` is only available from Sketch 49, nothing we can do about that.

More than 90% of Sketch users are on the latest 2 versions (eg 51 and 50). And that percentage is even higher if you look at the latest 3 versions (so >= 49). Up to you to decide if you want to support users using an older version

**Comment by tarunmangukiya** [comment]
Any alternative suggestions to make it work quickly? Or does it require to re-build plugin from scratch?
