### ISSUE TITLE
Security issue with 'open' dependency

### ISSUE THREAD

**Issue by romansp** [skpm/skpm#181]
So `npm audit` reports of a critical security issue in `skpm`, in particular dependency on `open` package: https://www.npmjs.com/advisories/663. It doesn't seem that this will ever be fixed in `open` itself.

There is an alternative package that can be used instead:
https://www.npmjs.com/package/opn

**Comment by mathieudutour** [comment]
Fixed in https://github.com/skpm/skpm/commit/656e2b3b285f603de10d2f4728a74296b9a0a25e
