### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by hrag** [skpm/skpm#185]
The immediate instructions after running `skpm create my-plugin --template=airbnb/react-sketchapp` gives you the instruction to run `npm run start` but there's no start script defined.

Either fix in package.json, or remove from the create commands and readme.

**Comment by mathieudutour** [comment]
Good point. I do like the instructions after the installation so we should probably fix the template. 

Do you want to open a PR on the react-sketchapp repo?

**Comment by hrag** [comment]
Oh, I was just referring to skpm in particular. I was using it independently. Looks like it's here: `https://github.com/skpm/skpm/blob/master/packages/skpm/src/commands/create.js`
