### ISSUE TITLE
skpm log -f returns immediately

### ISSUE THREAD

**Issue by robintindale** [skpm/skpm#186]
seems like `-f` is no longer tailing the log file

**Comment by robintindale** [comment]
hmm this is working again... something weird happened!

**Comment by lukasholzer** [comment]
`skpm log` does not return anything in my environment.
I found out that on my Machine is no log file that could be displayed…

*@skpm/internal-utils/tool-config.js*
`${homedir}/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log`

under Logs is no folder **com.bohemiancoding.sketch3** – so possibly the answer why it does not return anything. @robintindale Do you have this folder?

or any ideas how i can define the Plugin Output.log *(or find it if it exists)*?

**Comment by jdwolk** [comment]
I just ran into this myself. I manually created the dir and file, i.e.

```
mkdir -p ~/Library/Logs/com.bohemiancoding.sketch3 && touch ~/Library/Logs/com.bohemiancoding.sketch3/Plugin\ Output.log
```

Then when I ran `skpm log -f` things worked again 🤷‍♂️

**Comment by mathieudutour** [comment]
yep, this is a Sketch bug and should be fixed in Sketch 54
