### ISSUE TITLE
Running sketchtool inside plugin causes kernel panics

### ISSUE THREAD

**Issue by thibmaek** [skpm/skpm#189]
When trying to run the following code in a plugin on a sketchfile with 1 artboard and that one made exportable, my computer (latest macOS, MBP 13" 2017) freezes and then kernel panics.

```js
const absolutePath = sketch.fromNative(context.document).path;

execSync(`/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool export slices ${absolutePath} --output /Users/thibault/ --format="png" --scales="1, 2, 3"`);
```

```console
$ npm start
bash: /usr/local/opt/node@8/bin/npm: /usr/bin/env: bad interpreter: Too many open files in system
bash: /Users/thibault/.pyenv/shims/powerline-shell: /usr/bin/env: badinterpreter: Too many open files in system
```

**Comment by mathieudutour** [comment]
I'm guessing there is an infinite loop somewhere. Why would you not use the [export](https://developer.sketchapp.com/reference/api/#export) API tho? `sketchtool` is made to run outside of Sketch

**Comment by thibmaek** [comment]
Yes, I did it that way now but nevertheless, I still think it shouldn't be able to cause a kernel panic. What is even weirder is that when I tried restarting Sketch after the bash error occurred, Sketch asked for Calendar and Contact permissions.

**Comment by thibmaek** [comment]
Also I was using sketchtool because the export API does not have a way to export all slices for the document or only slices for a layer. Instead it always exports the complete layer.
