### ISSUE TITLE
Require not working for user modules

### ISSUE THREAD

**Issue by markhorgan** [skpm/skpm#190]
In my main JS file I have something like this:
```
var SomeClass = require('./some-class');

export var handler = function() {
  const instance = new SomeClass();
  instance.hello();
}
```

It doesn't seem to work - I get `Object is not a constructor` but if I replace `require` with `import SomeClass from './some-class';` it works. If the class has just static methods, it works ok.

Is there anyway to use require for both Sketch and user modules?

**Comment by mathieudutour** [comment]
I'm guessing `var SomeClass = require('./some-class').default;` should work. Or you need to use `module.exports = ...` instead of `export default ...` for your class
