### ISSUE TITLE
skpm-test: Error: couldn't find the test results

### ISSUE THREAD

**Issue by ryenbeatty** [skpm/skpm#191]
Hi there,

When running the example sum.js test, the following error is returned:
```Error: couldn't find the test results```

A quick look into the code showed me that the std.on('data') listener was not being called, hence the error. Happy to dive into this further if you can give some pointers.

Thanks!

**Comment by mathieudutour** [comment]
Hum I'm not able to reproduce. I'm using the `skpm-test` extensively on https://github.com/BohemianCoding/SketchAPI. Could you upload a repro?

**Comment by ryenbeatty** [comment]
It looks like that was happening due to a slightly outdated version of the sketch-dev-tools package! Not sure why that would happen, but maybe it's useful to you. Upgrading that package has solved the issue and now everything is working as expected.

**Comment by mathieudutour** [comment]
Hum that is weird indeed. Glad that you found a fix!
