### ISSUE TITLE
wrongly detects version & asks to update

### ISSUE THREAD

**Issue by detj** [skpm/skpm#195]
I upgraded skpm using `npm update -g skpm`, then ran `skpm create my-plugin`, it created the scaffold, but also showed the update message despite of being on the latest version.

<img width="589" alt="screenshot 2018-11-28 16 38 04" src="https://user-images.githubusercontent.com/280236/49147933-07d04380-f32c-11e8-8b65-f1d1cac2cda1.png">

Either, the update checker is detecting the wrong version or somehow the older version of skpm was run when I ran `skpm create my-plugin`. Not sure which is the case.

**Comment by mathieudutour** [comment]
It's a bug with [update-notifier](https://github.com/yeoman/update-notifier#readme). I updated it and hopefully it won't happen again
