### ISSUE TITLE
Why not adding fs polyfill as a core package?

### ISSUE THREAD

**Issue by aleen42** [skpm/skpm#200]
Since there was a polyfill for `fs` within NodeJS system, why don't you add it as a core package, in order to alias it inside Webpack? I hope to create a plugin where I can zip some analysed data locally.

**Comment by mathieudutour** [comment]
Because it's not ready yet. There is no support for streams and no support for the async API. Feel free to add support for that and I'll gladly add it as a core package :)

**Comment by aleen42** [comment]
@mathieudutour I have tried, but get the following error:

```
NSInvalidArgumentException: fs is not a core package
```

**Comment by mathieudutour** [comment]
Yes it is not ready yet so it’s not included.

**Comment by aleen42** [comment]
Yesterday, I have tried to read asynchronously through NSFileHandle, but get an empty data, do you know why? @mathieudutour 

```js
module.exports.readFile = function(path, options, callback) {
  var fileInstance = NSFileHandle.fileHandleForReadingAtPath(path)
  var notificationCenter = NSNotificationCenter.defaultCenter()
  var observerInstance = new Delegate({
    'onReadCompleted:': function(notification) {
      // empty string
      console.log(Buffer.from(notification.userInfo().NSFileHandleNotificationDataItem).toString('utf8'))
      // need to unregister the observer after callback
      notificationCenter.removeObserver_name_object(
        observerInstance,
        NSFileHandleReadToEndOfFileCompletionNotification,
        nil
      )
    }
  }).getClassInstance();

  notificationCenter.addObserver_selector_name_object(
    observerInstance,
    NSSelectorFromString('onReadCompleted:'),
    NSFileHandleReadToEndOfFileCompletionNotification,
    nil
  )

  fileInstance.readToEndOfFileInBackgroundAndNotify()
}
```

**Comment by aleen42** [comment]
I have solved by converting `OS_dispatch_data` like the following snippet, and any easier way?

```js
var dispatchData = notification.userInfo().NSFileHandleNotificationDataItem
NSString.alloc().initWithData_encoding(dispatchData, NSISOLatin1StringEncoding)
        .dataUsingEncoding(NSISOLatin1StringEncoding)
```

**Comment by mathieudutour** [comment]
That's already what `Buffer.from` should do: https://github.com/skpm/buffer/blob/master/index.js#L268-L284

Could you log `String(dispatchData.className())` to understand what is its class? Maybe `Buffer` doesn't recognize that it's an NSData

**Comment by aleen42** [comment]
I have got `OS_dispatch_data` with logging `String(dispatchData.class())`

**Comment by aleen42** [comment]
Another question is how can I expect something in test cases when calling methods asynchronously?

```js
test('should read a file', (context) => {
  readFile(getScriptFolder(context) + '/test/test.txt', {encoding: 'utf8'}, data => {
    // not work
    expect(data).toBe('abc')
  })
})
```

**Comment by mathieudutour** [comment]
I should indeed.

You need to return a promise:
```js
test('should read a file', (context) => {
  return new Promise((resolve, reject) => readFile(getScriptFolder(context) + '/test/test.txt', {encoding: 'utf8'}, data => {
    // not work
    expect(data).toBe('abc')
    resolve()
  }))
})
```

**Comment by mathieudutour** [comment]
I started a PR: https://github.com/skpm/fs/pull/12

It's needs proper error handling but at least it's working

**Comment by mathieudutour** [comment]
I don't think it's possible without Obj-C. What kind of code did you have in mind?

**Comment by aleen42** [comment]
By researching some documents, I think GCD is the only way of implementing asynchronous writing data within files.

**Comment by mathieudutour** [comment]
I'm going to close this as it's not an skpm issue. Let's discuss more in skpm/fs if needed
