### ISSUE TITLE
Question- forget about cocoascript on your webpage

### ISSUE THREAD

**Issue by mdonogma** [skpm/skpm#201]
What exactly does forget about cocoascript if you use Skpm? These are words from your skpm.io webpage 
There is a very import function that cocoascript has for events like button click or text view change called 

setCOSJSTargetFunction:function(sender) {
    userClickedOK = true
}];

How do I create click events like this on controls without setCOSJSTargetFunction?

**Comment by mathieudutour** [comment]
the bridge is still working. It's the cocoascript syntax that is disabled by default (using brackets to call functions and such)

**Comment by mdonogma** [comment]
Appreciate the response but it’s still not clear how to get it to work when skpm is used. Do you have an actual example plugin or can you indicate what needs to be updated in the call above for a button click to be called.

**Comment by mathieudutour** [comment]
it's exactly the same thing as before. Do you have an error showing up?

**Comment by mdonogma** [comment]
Using the latest version of sketch and it simply doesn’t respond. The panel build, the button is added but the click event doesn’t fire the function .

No error in log either- hence I’m looking for a working example of this when skpm is used as the theory is the function should fire but simply doesn’t. 

Try it yourself and you will see it doesn’t work.

Here is the link to the code that doesn’t use skpm however I moved it over to a skpm project and panel shows with controls exception function on button simply doesn’t respond.

Given there are no working examples on the internet of skpm + setCOS.... function being used together plus I can see it doesn’t work I think there is a bug here sketch team need to check.

This is going to be a blocker for any sketchapp developer that wants to create custom buttons in the right panel using skpm - please can sketch look into this further.

If the bridge to fire button events still works please point me to an sketch team example showing it works else there is no way to confirm /verify it is actually working with skpm

**Comment by mdonogma** [comment]
Here’s the link to the pro skpm project 

https://github.com/mludowise/sketch-panel-example/blob/master/sketch-panel-example.sketchplugin/Contents/Sketch/PanelManager.js

**Comment by mdonogma** [comment]
I’ve gone through all the examples regarding the sketchapp javascript api that are provided by sketchapp team and none of them have skpm with custom buttons calling custome functions via setCOSJSfunction etc..

**Comment by mathieudutour** [comment]
like I said, this is the same as before. If it doesn't work it's because there is a bug in your code. I took your project and moved it to skpm. It works fine: https://github.com/mathieudutour/panel-test.

**Comment by mdonogma** [comment]
Thank you so much. This will help many developers using skpm

**Comment by FRSgit** [comment]
@mdonogma sorry to reopen this issue, but repo link responds with 404 :< Do you have, by any chance, some copy of it?

**Comment by mdonogma** [comment]
Not sure if I do- eventually gave up.  I’ll dig around and check

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
