### ISSUE TITLE
Test runner cannot find the result

### ISSUE THREAD

**Issue by aleen42** [skpm/skpm#202]
When testing with some modules of `skpm`, I have found that the test runner will throw the following error when `sketch-dev-tools` was opened at the same time, and in detailed, I found that `child_process` won't fire its registered callback.

```
Error: couldn't find the test results
```

**Comment by mathieudutour** [comment]
Ah yes, `sketch-dev-tools` is eating the logs when it's opened. It should be fixed in Sketch 53 IIRC.

That's not really a bug for skpm to solve so I'll close this
