### ISSUE TITLE
skpm-build: command not found

### ISSUE THREAD

**Issue by jane00** [skpm/skpm#203]
sh: skpm-build: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! my-plugin@0.1.0 build: `skpm-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the my-plugin@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-01-25T09_30_55_844Z-debug.log
Jiao-Wangs-mac:my-plugin admin$

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.2.0
3 info using node@v10.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle my-plugin@0.1.0~prebuild: my-plugin@0.1.0
6 info lifecycle my-plugin@0.1.0~build: my-plugin@0.1.0
7 verbose lifecycle my-plugin@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle my-plugin@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/admin/my-plugin/my-plugin/node_modules/.bin:/Users/admin/Library/Android/sdk/emulator/:/Users/admin/Library/Android/sdk/tools/:/Users/admin/Library/Android/sdk/platform-tools/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/admin/Library/Android/sdk/emulator/:/Users/admin/Library/Android/sdk/tools/:/Users/admin/Library/Android/sdk/platform-tools/
9 verbose lifecycle my-plugin@0.1.0~build: CWD: /Users/admin/my-plugin/my-plugin
10 silly lifecycle my-plugin@0.1.0~build: Args: [ '-c', 'skpm-build' ]
11 info lifecycle my-plugin@0.1.0~build: Failed to exec build script
12 verbose stack Error: my-plugin@0.1.0 build: `skpm-build`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
13 verbose pkgid my-plugin@0.1.0
14 verbose cwd /Users/admin/my-plugin/my-plugin
15 verbose Darwin 17.7.0
16 verbose argv "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/bin/npm" "run" "build"
17 verbose node v10.8.0
18 verbose npm  v6.2.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error my-plugin@0.1.0 build: `skpm-build`
23 error spawn ENOENT
24 error Failed at the my-plugin@0.1.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by mathieudutour** [comment]
can't really help you there...

How did it happen? How can I reproduce? Did you install `@skpm/builder` by running `npm install`?

**Comment by mathieudutour** [comment]
well you need to install it at the beginning, so you need internet at least the first time
