### ISSUE TITLE
How does the changelog.json -> html conversion work?

### ISSUE THREAD

**Issue by epicfaace** [skpm/skpm#216]
How is this file (https://github.com/skpm/skpm/blob/master/packages/skpm/changelog.json) converted into the beautiful release notes here: https://skpm.io/release-notes/

Is this some library you are using, or custom-built for skpm?

**Comment by mathieudutour** [comment]
custom-built, really nothing special: https://github.com/skpm/website/blob/master/release-notes/index.html
