### ISSUE TITLE
Error in command, does not declare a run handler

### ISSUE THREAD

**Issue by REEMERGEMEDIA** [skpm/skpm#217]
I have a plugin using sketch module web view and have just added an action to listen to selection changes. Since adding this action I see that it's running from the output in the console, but my web view no longer launches with the console reporting the following error:

> Error in command My Plugin Script at path ... my-plugin-command.js does not declare a run handler.

I've read through the existing closed issues covering this error and still can't seem to find a solution. The end goal is to relay information from various actions to the web view. Here is my manifest.json. 

```json
"commands": [
  {
    "name": "My Plugin",
    "identifier": "my-plugin-identifier",
    "script": "./my-plugin-command.js",
    "handlers" : {
      "actions": {
        "SelectionChanged.finish": "onSelectionChanged"
      }
    }
  }
],
"menu": {
  "title": "my-plugin",
  "items": [
    "my-plugin-identifier"
  ],
  "isRoot": true
}
```

In the plugins main file the web view is exported as the default whereas the action handlers are simply exported.

```javascript
export function onSelectionChanged(context) { 
    // ...
}

export default function() { 
    var browserWindow = new BrowserWindow({})
    // ...
}
```

Is there a recommended solution for achieving this?

**Comment by mathieudutour** [comment]
when you specify a handler, the default one doesn't exist anymore. So you need to also specify a Run handler:

```diff
"handlers" : {
      "actions": {
        "SelectionChanged.finish": "onSelectionChanged"
-      }
+      },
+     "run": "onRun"
    }
```

**Comment by REEMERGEMEDIA** [comment]
@mathieudutour Thank you for pointing this out as adding the handler corrected the error I was experiencing. When looking through the docs on the [Plugin Guide](https://developer.sketch.com/guides/plugin-bundles/#plugin-commands) the Handler section makes mention of multiple command handlers in the same script, but does not reference including a specific run handler in situations as here. Thanks.
