### ISSUE TITLE
Export type json not working for some users

### ISSUE THREAD

**Issue by tarunmangukiya** [skpm/skpm#218]
Recently, I've noticed one strange thing with Sketch APIs. I am trying to export `svg`, `png`, `pdf` and `json` of selected layers. This code is working perfect and exporting all the file types for my device.

Code we're using
```js
const exportSelections = () => {
  const exportFormats = [
    'png',
    'svg',
    'json',
    'pdf'
  ]

  const document = sketch.getSelectedDocument()
  const selection = document.selectedLayers

  const fileManager = NSFileManager.defaultManager();
  const pathId = NSCachesDirectory;
  const paths = fileManager.URLsForDirectory_inDomains(pathId, NSUserDomainMask);

  // /Users/apple/Library/Caches/com.iconscout.icondrop.sketch
  const filePathBase = `${paths.objectAtIndex(0).path()}/sketch-temp`;

  const files = selection.map(layer => {
    sketch.export(layer, {
      formats: exportFormats,
      output: filePathBase,
      overwriting: true
    })

    return exportFormats.map(f => `${filePathBase}/${layer.name}.${f}`)
  })

  console.log('Exported Files:', files)

  return files
}
```

But on the device of one of our designer, it's not exporting `json` (not throwing errors). Also, there's no proper response of the `export` method using which I can detect that the selection is exported for `json`.

Then I copied that particular `.sketch` file to my device and it worked to export `json` format. Any help on this?

**Comment by mathieudutour** [comment]
That's not really an skpm issue, but the json export has been added in Sketch 53 IIRC so on older version of Sketch, it won't work
