### ISSUE TITLE
Allow shortVersionString in app cast

### ISSUE THREAD

**Issue by WCByrne** [skpm/skpm#220]
This would require some changes to Sketch itself but it would be great if app casts could make use of both `sparkle:version` and `sparkle:shortVersionString`. In my case I would like to make version the build number and shortVersionString the version to display.

**Comment by WCByrne** [comment]
Along with this, it would be great to be able to provide release notes to be shown for updates.

**Comment by mathieudutour** [comment]
I'm not sure why you need to publish the build number?

> Along with this, it would be great to be able to provide release notes to be shown for updates.

That's planned for the plugin registry (soon!)

I'm going to close the issue because that's really not something skpm can do anything about but we can continue the conversion here for sure

**Comment by WCByrne** [comment]
Regarding the version. We have a beta/alpha version of the plugin where we don't want to change the version string for every release but want it to update.

**Comment by mathieudutour** [comment]
Hum I think it'd be easier to go with semver: `3.0.0-beta1`, etc.

**Comment by WCByrne** [comment]
I can go that route too if this isn't something you want to do. Thanks.

**Comment by mathieudutour** [comment]
We are trying to bring the dev experience as close to Node as possible so it makes sense to go with semver instead of build number
