### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by DrinkingWords** [skpm/skpm#221]
What is the difference between "assets/", "assets/*" and "assets/**/*" ?
Is there any requirements for the files in assets folder?
I have two files. One is written by "h5" and the other is written by "vue.js". So I add the following line to the package.json, But the plugin can not be updated by "appcast".
"assets": [ "assets/**/*",  "../panel/dist" ]

**Comment by mathieudutour** [comment]
Do you have a repo that I could try?

**Comment by DrinkingWords** [comment]
I am sorry that I can not supply the repo, Because It is not allowed. The problem has been solved. I accidentally used some pictures with Chinese name. I am so sorry for bothering you. Thank you for your help!
