### ISSUE TITLE
debugger

### ISSUE THREAD

**Issue by DrinkingWords** [skpm/skpm#224]
Here is part of my package.json:
"scripts": {
    "build": "skpm-build",
    "build-production": "cross-env NODE_ENV=production skpm-build",
    ...
}
In Safari, I go to Develop > name of my machine > Automatically Show Web Inspector for JSContexts and enable Automatically Pause Connecting to JSContext. In addition, there is a "debugger" in my code.
When the command is "npm run build", the JavaScript context pause in debugger position, then I can use breakpoints in safari.  But when the command is "npm run build-production", the JavaScript context does not pause. so I can not see my code and can not use breakpoints in safari.

**Comment by mathieudutour** [comment]
I found that the "automatically Pause connection to JSContext" is a bit broken at times indeed.

But I think that when you run `NODE_ENV=production skpm build`, it strips out `debugger`. So it won't stop by itself

**Comment by mathieudutour** [comment]
I'm not sure that's an issue with skpm tbh

**Comment by DrinkingWords** [comment]
Indeed it is. When I run skpm build, there are .js files and .js.map files in Contents/sketch and there is 'debugger' in .js files. But when I run NODE_ENV=production skpm build，there are only .js files in Contents/sketch and there is no 'debugger' in .js files. It may be an issue with npm. Thank you so much.

**Comment by mathieudutour** [comment]
It's not an issue with npm either.

It's just the expected behaviour when you use `NODE_ENV=production` for the default skpm config. If you want to change that behaviour, then you modify the webpack config: https://github.com/skpm/skpm/blob/master/docs/build-configuration.md#webpack
