### ISSUE TITLE
npm start will evaluate every script referenced in menu

### ISSUE THREAD

**Issue by c5inco** [skpm/skpm#225]
I notice sometimes when I `npm start` my plugin, Sketch will open and then every single script referenced in my menu config in the manifest will evaluate.

It seems broken and causes a lot of broken state while iterating on developing the plugin.

Has anyone else run into this issue?

**Comment by mathieudutour** [comment]
you can use `npm run watch` to avoid running the scripts. how do you expect skpm to know which script to run or not to run?

**Comment by c5inco** [comment]
Oh I see - that makes sense!  I guess I wouldn't expect `start` to run any specific script/command per se, unless it was set to the default (which was my first use case when I only had one command in my plugin).

What threw me off further was that sometimes `npm start` would build and run the plugin and NOT execute any scripts, but then other times it would execute all of them.  Not sure if that's intentional.
