### ISSUE TITLE
Watch mode doesn't work with `--run` 

### ISSUE THREAD

**Issue by aswinckr** [skpm/skpm#226]
Doing `npm run watch` works when I make any changes.

Doing `npm run start` doesn't watch for changes and rebuild when I make any changes. 

Running `npm run start` for the first time opens sketch but plugin doesn't run automatically even the first time, I need to run it manually. Am i missing something?

**Comment by aswinckr** [comment]
On my logs i get `os is not a core package`

**Comment by mathieudutour** [comment]
If your plugin is asynchronous, then `--run` won't work. It will work in Sketch 56 tho

**Comment by aswinckr** [comment]
I just use the starter code. Is this asynchronous by default?

```
import sketch from 'sketch'
// documentation: https://developer.sketchapp.com/reference/api/

export default function (context) {
  context.document.showMessage("its alive!!");
  print(context);
}
```

**Comment by Maikenvv** [comment]
I have the same issue with the default code. @aswinckr Did you ever find a solution for this?

**Comment by afnizarnur** [comment]
Got the same issue too.

**Comment by corysimmons** [comment]
It's still doing this. Thank god `npm run watch` works as expected or I could never get through developing a plugin. Weird bug.
