### ISSUE TITLE
Confusing output

### ISSUE THREAD

**Issue by KevinGutowski** [skpm/skpm#228]
![Screen Shot 2019-05-18 at 4 17 06 PM](https://user-images.githubusercontent.com/4199296/57975899-86777680-7988-11e9-8d1a-aa358e3f484a.png)

I’m a little confused about what is going on here for a couple of reasons.

1.) The error here is reporting lines of compiled code which is making things difficult to track down.
2.) I think this might be a bug with the `sendToWebview` function?

**Comment by KevinGutowski** [comment]
Here is a link to my code: https://gist.github.com/KevinGutowski/03ea367d00ac593217cf6770ee1cc539

**Comment by KevinGutowski** [comment]
In fact, if I just create a fresh SKPM project and just add 
```
console.log("hello")
```

I get the same error
![Screen Shot 2019-05-18 at 4 17 06 PM](https://user-images.githubusercontent.com/4199296/57975934-ace9e180-7989-11e9-97fe-74da12e2f0c8.png)
Maybe its an issue with DevTools

**Comment by mathieudutour** [comment]
Hum I can't find that method anywhere. What version of sketch-dev-tools are you using?

**Comment by KevinGutowski** [comment]
hmm 0.9.5

**Comment by mathieudutour** [comment]
weird... IIRC it was used in the version 0.8 but not anymore. Could you try removing the sketch-dev-tools plugin and adding it again?

**Comment by KevinGutowski** [comment]
hmm must be something with my plugin that I created earlier… I just created another new project from stratch, reinstalled dev-tools, and now the error is gone. I still get the error with my old project though so I’m just going to scrap it and move my code over to the newer project ¯\_(ツ)_/¯
