### ISSUE TITLE
Allow npm dependencies to drop stuff into Resources/

### ISSUE THREAD

**Issue by romannurik** [skpm/skpm#231]
Sketch plugin libraries like [sketch-toolbar-item](https://github.com/abynim/sketch-toolbar-item) require you to add a `.framework` bundle to your plugin's `Resources` folder. `skpm` lets you automate that a little bit with fields in `package.json`, but I wonder if it'd be useful to allow npm packages in your dependencies list to add stuff to your `Resources`... then, all you'd need to do to bring in a library like `sketch-toolbar-item` is `npm install --save` it, and then `import` its JS API in your plugin's JS code. That'd be cool!

**Comment by mathieudutour** [comment]
Ah good timing!
I just added a new webpack loader to import xcodeproj: https://github.com/skpm/xcodeproj-loader.

So you could have an js file that just do 
```js
module.export = require('./path/to/xcodeproj').getClass('SketchToolbarIcon')
```
and publish it to npm with the xcodeproj.

One thing to note tho: frameworks will need to be signed on macOS 10.15 so sharing xcodeproj will become harder if you aren't on the same apple dev team.

Another thing to note: importing a framework directly is tricky because a framework is a folder and webpack doesn't want to import a folder. So you need to import a file inside the framework. The default skpm config won't match any file inside because they are too generic (usually just a binary and a plist).
So instead you need to force the loader:
```js
module.export = require('@skpm/xcodeproj-loader?raw=true&publicPath=_webpack_resources&outputPath=../Resources/_webpack_resources!./SketchToolbarIcon.framework/SketchToolbarIcon').getClass('SketchToolbarIcon')
``` 
and unfortunately, you need to specify the config of the loader inline, it won't pick up the default config

**Comment by mathieudutour** [comment]
I just tried it on sketch-toolbar-item and it looks great:
```js
import sketch, { UI } from 'sketch'
import SketchToolbarIcon from './sketch-toolbar-icon'

// Handlers for the toolbar item's run action
export function sayHello() {
    UI.alert('Hello from the toolbar!', 'Have a great day 👋')
}

export function sayNamaste() {
    UI.alert('Namaste from the toolbar!', 'Be cool 🙏')
}

export function sayGoodbye() {
    UI.alert('Goodbye from the toolbar!', 'See ya later, maybe ✌️')
}

// The handler for the toolbar item's validate action
// If this method is not implemented, your toolbar item is always enabled
// NOTE: Keep this method light. Doing too much here will slow down Sketch
export function validateToolbarItem(context) {

  // Get a reference to your toolbar item via context
  let toolbarItem = context.toolbarItem

  let doc = sketch.getSelectedDocument()
  let selectedLayers = doc.selectedLayers

  // As an example: enable the toolbar item if selection is not empty
  toolbarItem.enabled = !selectedLayers.isEmpty


  // To change the item's icon during validation,
  // pass a relative path to another 32x32px image in your plugin's Resources folder:
  // This is entirely optional!

  // toolbarItem.iconImagePath = selectedLayers.isEmpty ? "hello-toolbar-icon-flipped.png" : "hello-toolbar-icon.png";
}

export function registerToolbarActions(context) {
  // register a single toolbar item by passing:
  // 1. the current context
  // 2. the command identifier of the action this item will trigger
  // 3. the relative path to a 32x32px icon image in your plugin's Resources folder

  // To add a different image for dark mode, separate the image paths with a |

  SketchToolbarIcon.registerToolbarAction_commandID_iconImagePath(context, 'goodbye', 'goodbye-toolbar-icon.png|goodbye-toolbar-icon-dark.png');

  // to register a group of items, create specifiers for each item then register them as a group
  let item1 = SketchToolbarIcon.specifierForToolbarAction_commandID_iconImagePath(context, 'namaste', 'namaste-toolbar-icon.png|namaste-toolbar-icon-dark.png');
  let item2 = SketchToolbarIcon.specifierForToolbarAction_commandID_iconImagePath(context, 'hello', 'hello-toolbar-icon.png|hello-toolbar-icon-dark.png');

  SketchToolbarIcon.registerToolbarGroup_identifier_specifiers(context, 'salutations', [item1, item2]);


  // to register a toolbar item with a dropdown menu, create a menuItem for each sub-item
  let menuItem1 = SketchToolbarIcon.menuItemForToolbarAction_commandID_iconImagePath(context, 'hello', 'hello-toolbar-icon.png|hello-toolbar-icon-dark.png');
  let menuItem2 = SketchToolbarIcon.menuItemForToolbarAction_commandID_iconImagePath(context, 'namaste', 'namaste-toolbar-icon.png|namaste-toolbar-icon-dark.png');
  let menuItem3 = SketchToolbarIcon.separatorMenuItem();
  let menuItem4 = SketchToolbarIcon.menuItemForToolbarAction_commandID_iconImagePath(context, 'goodbye', 'goodbye-toolbar-icon.png|goodbye-toolbar-icon-dark.png');

  // Then register them using the `registerToolbarMenu` method
  SketchToolbarIcon.registerToolbarMenu_identifier_title_iconImagePath_menuItems(context, 'greetings', 'Greetings', 'greetings-toolbar-icon.png|greetings-toolbar-icon-dark.png', [menuItem1, menuItem2, menuItem3, menuItem4]);
}
```

and the sketch-toolbar-icon.js file:
```js
export default require('@skpm/xcodeproj-loader?raw=true&publicPath=_webpack_resources&outputPath=../Resources/_webpack_resources!./SketchToolbarIcon.framework/SketchToolbarIcon').getClass('SketchToolbarIcon')
```

with the framework next to it

**Comment by mathieudutour** [comment]
I also need to add that using a framework directly can be pretty dangerous, you can't inspect the source so it could do anything (stealing your data, etc.) (not that I think @abynim would do it but...). That's true if you are using the framework as well but here you would be spreading the risk to all your users.

**Comment by abynim** [comment]
Wow this is awesome! Thanks for pretty much building the package for me. I have it working locally, now looking into publishing this. 

I’ve never published a package to npm 😱 Guess I can update the skills on my resumé if I can get through!

And yes, one of the reasons I don’t want to make the source public is the privacy risk you mentioned. With the source being private, I can sign the framework myself so users+developers will know they can trust it. Probably makes sense to also include a privacy policy in there to make it clear.

**Comment by mathieudutour** [comment]
Ah if you want to publish it, you might need
```js
module.export = require('@skpm/xcodeproj-loader?raw=true&publicPath=_webpack_resources&outputPath=../Resources/_webpack_resources!./SketchToolbarIcon.framework/SketchToolbarIcon').getClass('SketchToolbarIcon')
```
instead of the `export default`.

> one of the reasons I don’t want to make the source public is the privacy risk you mentioned

Hum I'd say that the opposite is true? If you publish the source, devs can know what you put inside and don't have to rely on trust?
