### ISSUE TITLE
`skpm-build` ignores relative paths of `commands`

### ISSUE THREAD

**Issue by yuanqing** [skpm/skpm#240]
- Version: `@skpm/builder@0.7.0`

This is a problem only when we have commands where the file name referred to by their `script` happens to be the same. [See this repo.](https://github.com/yuanqing/skpm-240)

In the input [`src/manifest.json`](https://github.com/yuanqing/skpm-240/blob/master/src/manifest.json), there are two commands with different `identifier` and different `script` (but the file names happen to both be `my-command.js`):

```
{
  // ...
  "commands": [
    {
      "name": "foo",
      "identifier": "my-plugin.foo",
      "script": "./my-command.js"
    },
    {
      "name": "bar",
      "identifier": "my-plugin.bar",
      "script": "./bar/my-command.js"
    }
  ],
  // ...
}
```

After running `skpm-build`, [the output plugin bundle only contains one `my-command.js`](https://github.com/yuanqing/skpm-240/tree/master/my-plugin.sketchplugin/Contents/Sketch). The `bar/` relative path appears to have been ignored, and the output file of the second `my-plugin.bar` command overwrites the output file of the first `my-plugin.foo` command.

Below is the [`manifest.json` in the output plugin bundle](https://github.com/yuanqing/skpm-240/blob/master/my-plugin.sketchplugin/Contents/Sketch/manifest.json). The `bar/` relative path of the second command’s `script` field is missing.

```
{
  // ...
  "commands": [
    {
      "name": "foo",
      "identifier": "my-plugin.foo",
      "script": "my-command.js"
    },
    {
      "name": "bar",
      "identifier": "my-plugin.bar",
      "script": "my-command.js"
    }
  ],
  // ...
}
```

# Possible solutions

Unsure if this is some configuration that I’m missing or getting wrong. If not, some possible solutions would be:

1. Make `skpm-build` always preserve relative paths in the built output, or
2. Make it explicit in the docs that relative paths are omitted and that file names used in `script` must be unique, and perhaps do validation and throw an error if we detect otherwise

**Comment by mathieudutour** [comment]
That’s definitely a bug, thanks for the nice bug report!
