### ISSUE TITLE
skpm builder resourceLoader tries to bundle md files

### ISSUE THREAD

**Issue by macintoshhelper** [skpm/skpm#242]
Hi! I have a small bug/issue:

I'm working on implementing the `mdx` React markdown loader into a `react-sketchapp` project and added a custom Webpack rule, but was left with Sketch crashing.

After some debugging, I traced the issue to `resourceLoader` trying to bundle the `.md`. I was wondering whether `md` and `mdx` could be added to the ignore regex, or if you'd have any idea on a way to allow for manual overrides?

https://github.com/skpm/skpm/blob/master/packages/builder/src/utils/resourceLoader.js#L5

Thanks!

**Comment by mathieudutour** [comment]
You can update the webpack config that skpm uses: https://github.com/skpm/skpm/blob/master/docs/build-configuration.md#webpack
