### ISSUE TITLE
Feature to build with just webpack

### ISSUE THREAD

**Issue by jorenbroekema** [skpm/skpm#244]
Hey.

I don't want to pretend to understand what goes on in skpm-builder but I'm wondering whether it would be possible to just build the .sketchplugin by running `webpack` itself, rather than through skpm-builder. 

Right now it gives you the webpack.skpm.config.js to provide webpack overrides, but I would prefer having a skpm webpack config I can extend, and run `webpack` directly, instead of through a custom command.

The use-case here for me is mostly related to security, where the pipelines I work with will only allow building/bundling by the use of `webpack` command. So in my scenario, any webpack-compatible configuration, no matter how crazy, is completely fine, but a custom script is not :\

**Comment by mathieudutour** [comment]
skpm is really just a webpack config, you can find it here: https://github.com/skpm/skpm/blob/master/packages/builder/src/utils/webpackConfig.js

Not sure how you can extract it tho. I do expose `require('@skpm/builder').webpackConfig` but I'm not going to document it too much, it's pretty much an internal API. I use it here https://github.com/skpm/sketch-dev-tools/blob/master/assets/build-script.js if you want an example

**Comment by jorenbroekema** [comment]
I'm a bit confused about the webpackConfig, it is called by the build-script:
```js
generateWebpackConfig(
  {},
  path.join(process.cwd(), './.scripts'),
  path.join(process.cwd(), './.scripts'),
  {}
)({
  isPluginCommand: true,
  script: path.basename(process.argv[2]),
  absolutePath: process.argv[2],
  handlers: ['onRun'],
});
```
This returns a Promise which you should be able to use with webpack directly, correct?

The part that confuses me is `process.argv[2]`, what is this argument? I get the feeling it is not suitable to just use this code inside a webpack.config.js and expect it to work for your sketch plugin with the `webpack` command, and it's not very clear to me what's necessary to make it work, if it's even possible.

**Comment by mathieudutour** [comment]
`process.argv[2]` is the absolute path to the entry
