### ISSUE TITLE
Notarization .skpmrc not recognized?

### ISSUE THREAD

**Issue by wousser** [skpm/skpm#248]
I wanted to sign my plugin, followed the instructions on notarization.md
- Added .skpmrc next to package.json
- Ran skpm publish minor
Error message:
```
The plugin won't be notarized because the configuration is missing.
```

Is there anything else that needs to be done? Does it not work for minor releases?

**Comment by mathieudutour** [comment]
Oh there is a typo in the docs, the key in the configuration needs to be `notarisation` and not `notarization`. 
I'll fix it to support both

**Comment by mathieudutour** [comment]
fixed in https://github.com/skpm/skpm/commit/fd109793fb962fd9528d18f5758fd765a0b25265
