### ISSUE TITLE
Test runner - how to spy module's function?

### ISSUE THREAD

**Issue by FRSgit** [skpm/skpm#250]
Hey,

I'm trying to bring tests to our plugin's codebase, but have one problem with that - I see no possibility to stub imported modules/files. Here is a minimal reproduction example of the issue I'm facing:

toolbar.js:
```javascript
export function closeToolbar () {
  /* some production implementation */
}
```

apiClient.js:
```javascript
import { closeToolbar } from '../toolbar';
class APIClient () {
  static handleError (res) {
    if (res.status === 403) {
      closeToolbar();
    }
  }
}
```

apiClient.spec.js
```javascript
import { APIClient } from './api_client';
let toolbar = require('../toolbar');

let closeToolbarSpy;

beforeEach(() => {
    closeToolbarSpy = sinon.spy(toolbar, 'closeToolbar');
});

test('handleError when request fails with status=403 should call closeToolbar', () => {
    const res = {status: 403};
    APIClient.handleError(res);

    expect(closeToolbarSpy.calledOnce).toBe(true);
});
```

But unfortunately when running test I always get an error:
`Attempted to wrap undefined property closeToolbar as function`

But well, `console.log(toolbar.closeToolbar);` logs correctly, so the method is there.
As I've digged into the problem I found [this issue](https://github.com/sinonjs/sinon/issues/1711). After doing some checks, it's true - method `closeToolbar` imported by webpack is always and unconfigurable getter, and probably that's why sinonjs fails. I've tried to use packages like [rewire](https://www.npmjs.com/package/rewire) or [proxyquire](https://www.npmjs.com/package/proxyquire) which should address this issue, but the just don't work (lot's of issues connected with `fs` package or `module` itself).

I've also tried thing like `jest-mock` but they don't seem to work as well.

The question raises - how should one stub/spy/mock his methods/classes so it would be possible to unit test them using `@skpm/test-runner`?

**Comment by mathieudutour** [comment]
That's a good question and I don't have the answer. Maybe changing the webpack config so that it doesn't create an unconfigurable getter?

**Comment by FRSgit** [comment]
@mathieudutour fixed it by adding babel transform (`@babel/plugin-transform-modules-commonjs`)
