### ISSUE TITLE
Write some docs about stubbing

### ISSUE THREAD

**Issue by mathieudutour** [skpm/skpm#252]
How to work with sinon and @skpm/test-runner?

**Comment by mathieudutour** [comment]
@FRSgit (can't seem to be able to assign you to the issue 🤔)

**Comment by FRSgit** [comment]
@mathieudutour  Hm, thought it would be possible. Nevertheless, mentioning was well enough 😄

**Comment by mathieudutour** [comment]
Now it works ¯\_(ツ)_/¯
