### ISSUE TITLE
Plugin keeps failing to notarize with Apple's error message "Package ... has no signed executables or bundles. No tickets can be generated."

### ISSUE THREAD

**Issue by romannurik** [skpm/skpm#261]
I'm following the [notarization docs](https://github.com/skpm/skpm/blob/master/docs/notarization.md) on a plugin **with no native frameworks** and running into the following cascade of errors when publishing an update:

1. `skpm publish` fails with this:

    ```
    $ skpm publish v0.2.6
    ⠙ Sending the plugin to be notarized
    ✖ ERROR TypeError: Cannot read property 'split' of undefined
    TypeError: Cannot read property 'split' of undefined
        at /usr/local/lib/node_modules/skpm/lib/commands/publish.js:282:254
        at Generator.next (<anonymous>)
        at step (/usr/local/lib/node_modules/skpm/lib/commands/publish.js:82:191)
        at /usr/local/lib/node_modules/skpm/lib/commands/publish.js:82:361
        at process._tickCallback (internal/process/next_tick.js:68:7)
    ```

    I think it's trying to parse out a RequestUUID even though `altool` is failing.

2. I get an email from Apple with the title **"Your Mac software was not notarized"**

3. The email includes a Request Identifier, and when I run `altool` to get more details on what went wrong: `xcrun altool -u "my@email.com" -p "@keychain:AC_PASSWORD" --notarization-info <uuid>` I get access to a log file with these details:

    ```
    statusSummary: "Archive contains critical validation errors"
    ...
    message: "Package 1575992567770.zip has no signed executables or bundles. No tickets can be generated."
    ```

When checking the ZIP file itself that skpm generated, I see a totally normal-looking .sketchplugin directory.

Any ideas?

**Comment by romannurik** [comment]
FWIW, removing `.skpmrc` results in a successful publish. My sense is we shouldn't be trying to notarize plugins that don't have binary executable code (i.e. plugins without a native framework)

**Comment by mathieudutour** [comment]
you're probably right, I changed the message a bit (the devops team at Sketch wanted to us to notarized all the plugins because it might have become mandatory later but if it fails, let's just not)

I also fixed the `split` error

**Comment by romannurik** [comment]
Awesome thank you!
