### ISSUE TITLE
Please help me!!! webview is automatically hidden when lose focus!!!

### ISSUE THREAD

**Issue by lovehanyang** [skpm/skpm#263]
I have tried many ways, but none of them have worked.

I am a Chinese developer.I am a java developer and this is the first time I make a plugin.

When I click on the desktop with the mouse, the webview is automatically hidden. I think this is caused by losing focus, but I don't want to. Because my webview is associated with the sketch, every time the webview is hidden, the sketch is also hidden.

So, how can I keep my webview from hiding when it loses focus?
Thank you very much, please help me

**Comment by mathieudutour** [comment]
duplicates from sketch-module-web-view
