### ISSUE TITLE
skpm installation fails with CERT_UNTRUSTED error

### ISSUE THREAD

**Issue by srotblatt** [skpm/skpm#265]
I just upgraded my MacOS to 10.15.2.  My node version is 0.10.21 and my npm version is 1.3.11.  When I run npm install -g skpm, I get a CERT_UNTRUSTED error.  Is this an issue with skpm or am I missing something?

**Comment by mathieudutour** [comment]
node 0.10? That's 5 years old, it's not supported anymore. Update to node 12 and npm 6 and it should work.
