### ISSUE TITLE
Proposal: Resolve jsx files

### ISSUE THREAD

**Issue by macintoshhelper** [skpm/skpm#270]
https://github.com/skpm/skpm/blob/55e448e96811a596fc04369d257cd2e4b6f8dd9c/packages/builder/src/utils/webpackConfig.js#L132

could be changed to:

```js
extensions: ['.sketch.js', '.js', '.sketch.jsx', '.jsx'],
```

Should I go ahead and submit a PR?

**Ref**
> https://github.com/airbnb/react-sketchapp/pull/483#discussion_r390444961

**Comment by mathieudutour** [comment]
yes please :)
