### ISSUE TITLE
Compiled Background image url format

### ISSUE THREAD

**Issue by oodesign** [skpm/skpm#275]
Hi!

I'm using skpm with webview.

On build, I'm getting CSS background-image properties formatted like this:

`background-image: url(d6ef1b4038db17b9d78a101b3eab8918.png";);`

Which in the webview trigger an error as it would expect

`background-image: url("d6ef1b4038db17b9d78a101b3eab8918.png");`

Am I doing anything wrong or missing any step/config?

Thanks a lot for your help! 🥰

**Comment by mathieudutour** [comment]
no it was the same bug as https://github.com/skpm/with-webview/issues/20 which should now be fixed
