### ISSUE TITLE
Publishing using environment variable

### ISSUE THREAD

**Issue by TheSonOfThomp** [skpm/skpm#276]
I'm trying to publish without logging in, and instead relying on the env variable.

I've set `GITHUB_ACCESS_TOKEN=xyx` in my `.env` file, and tried to run `skpm publish minor`, however I still get the error: 

```
✖ ERROR No Github API token found in keychain
skpm needs a GitHub token to be able to publish releases.
The token needs the `repo` permissions in order to create releases.

Run `skpm login <token>` or set the `GITHUB_ACCESS_TOKEN` environment variable.
```

I can publish after running `skpm login xyx` with no problem

**Comment by mathieudutour** [comment]
are you sourcing your .env file? Otherwise it doesn't do anything. You can try `source .env && skpm publish minor`
