### ISSUE TITLE
skpm publish does not add or update lastUpdated flag in plugin directory

### ISSUE THREAD

**Issue by abdulmhamid** [skpm/skpm#279]
After recently publishing a new Sketch [plugin](https://github.com/proteanstudio/sketch-palette-cleanser) (major and patch versions), I observed that no `lastUpdated` key is added to the object created in the [plugin directory file](https://github.com/sketchplugins/plugin-directory/blob/master/plugins.json). It appears as though items missing the `lastUpdated` key do not become visible on the [Sketch plugins](https://www.sketch.com/extensions/plugins/) page.

Please let me know if this assessment is incorrect or if I should seek to resolve this in another manner.  I observed that other recently added plugins are in a similar state and a newer plugin with a manually input `lastUpdated` date is appearing on the site.

**Comment by mathieudutour** [comment]
> It appears as though items missing the lastUpdated key do not become visible on the Sketch plugins page.

I wasn't aware of that. That's unfortunate given how it's annoying to have to create an update to the repo is while it could just fetch the manifest of the plugin.

cc @bomberstudios

**Comment by bomberstudios** [comment]
Thanks for the ping!

Currently, the `lastUpdated` attribute is updated / created automatically on the `plugins-directory` repo, using GitHub Actions. At the moment the Action runs weekly, but I'll see if we can make it run on merges too so that plugins are immediately shown on the website without having to wait for the cron job to run.

**Comment by mathieudutour** [comment]
I just had a quick look at the GH action and it's failing for about half of the plugins because of the GH API rate limit.

I'm going to close this issue because I don't think the solution is in skpm

**Comment by bomberstudios** [comment]
Definitely not an skpm issue, yeah. Will take a look at the rate limit issue, thanks for the warning!

**Comment by abdulmhamid** [comment]
Thanks for looking into this.

**Comment by bomberstudios** [comment]
FTR, this has been addressed in https://github.com/sketchplugins/plugin-directory/commit/4d16429d20a788eff3b93e47d23efc16135b27e8

@mathieudutour I could not see the rate limit issue you mentioned when checking the Actions log. We're using a GH token in the repo to work around that issue, and it might not be obvious if you run the task locally (it will still run, but Octokit won't authenticate the requests, thus throwing a rate limit error)
