### ISSUE TITLE
Publishing on OSX Big Sur

### ISSUE THREAD

**Issue by cyberalien** [skpm/skpm#287]
`skpm publish patch` used to work fine on older OSX, but after updating to Big Sur (and re-installing all node modules, including skpm), when attempting to publish I get error:

```
0 ~/Documents/dev/sketch/iconify-sketch skpm publish patch
⠹ Pushing the changes to Github
✖ ERROR Error: Command failed: git push -f origin HEAD 1.1.8
error: src refspec 1.1.8 does not match any
error: failed to push some refs to 'github.com:iconify/iconify-sketch.git'

Error: Command failed: git push -f origin HEAD 1.1.8
error: src refspec 1.1.8 does not match any
error: failed to push some refs to 'github.com:iconify/iconify-sketch.git'

    at ChildProcess.exithandler (node:child_process:309:12)
    at ChildProcess.emit (node:events:329:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
```

**Comment by bomberstudios** [comment]
FTR, I’m seeing this too on Catalina, so definitely not a Big Sur issue.

I initially thought it might be an issue with Homebrew’s git version, but uninstalling it and using Apple’s default throws the same error 🤔

**Comment by griffin-stewie** [comment]
same here. Is there any workaround?

**Comment by cyberalien** [comment]
> Is there any workaround?

I've been publishing plug-in updates manually. Process (change 2.0.0 to correct version number):
- Update version in package.json (or manifest.json if you have version number there)
- Build plugin, commit all changes (as usual before publishing)
- Add tag: `git add tag 2.0.0 -m "v2.0.0"`
- Push tag to GitHub: `git push origin 2.0.0`
- Go to releases (https://github.com/{username}/{repo}/releases), create new release:
  - Select tag "2.0.0"
  - Title: "v2.0.0"
  - Description: "Publish 2.0.0 release :rocket:"
  - Drag your plug-in from to "Attach binaries" field. I'm using Finder and Safari, which automatically zip it before uploading.
  - Publish release.
- Open .appcast.xml, copy first entry, change version number.
- Commit changes to .appcast.xml, push it to GitHub repo.

**Comment by griffin-stewie** [comment]
I think this problem is caused by a change in the output of `npm version`.

[Here](https://github.com/skpm/skpm/blob/9ffe5d6364bccdbe082451fcc6418f00e2d1150e/packages/skpm/src/commands/publish.js#L161
) is a part that call `npm version` command, and assign trimmed stdout into `tag` variable. There are lots of code that replacing 'v' from the `tag` variable. These codes tell us that output of `npm version` was like 'vX.Y.Z'.

Unfortunately, I think the problem is caused by the removal of the 'v' character from the `npm version` output, so it no longer matches the name of the git tag.

**Comment by mathieudutour** [comment]
looks like you're right, we should now add it if it's not there 🤔 (so `1.1.8` becomes `v1.1.8` and matches the created tag). Want to send a PR?

**Comment by griffin-stewie** [comment]
@mathieudutour 
I'm not very experienced with Node.js, so I need to learn how to debug. Could you tell me how to do that?
