### ISSUE TITLE
Sketch crushes after trying to load a plugin

### ISSUE THREAD

**Issue by Aleksandyr** [skpm/skpm#296]
Couldn't find what could be the reason because we've tried running the same sketch plugin on four different mac machines and it fails only on one.

We have tried [Why is the Mac app crashing? Try these solutions](https://www.sketch.com/support/troubleshooting/crash-troubleshooting/) without any success.
Plugin fails on **MacBook pro 2019** 

Can anyone tell what could get wrong based on this report?:
[sketch-crushes.docx](https://github.com/skpm/skpm/files/7452948/sketch-crushes.docx)

**Comment by mathieudutour** [comment]
I'm sure that's annoying but that's not related to this tool. Can you try contacting the Sketch support instead?
