### ISSUE TITLE
TextAlignment mistake  on apple silicon

### ISSUE THREAD

**Issue by 7revor** [skpm/skpm#297]
In sketch JSAPI and sketch-file-format-ts, text center alignment is value 2 and right is 1.
But on apple silicon, When I set the text alignment to center, JSAPI returns 'right' and Objective-C api returns 1 too.
I unzipped the .sketch file, the alignment of the corresponding text is indeed 2.
When I run sketch by Rosetta, It works correctly.

**Comment by mathieudutour** [comment]
This has nothing to do with skpm, let's keep https://github.com/skpm/skpm/issues/297 only
