### ISSUE TITLE
null is not an object (evaluating 'NSApplication.sharedApplication().orderedDocuments().firstObject().showMessage')

### ISSUE THREAD

**Issue by dongjinc** [skpm/skpm#301]
when sketch opened, hint me  => null is not an object (evaluating 'NSApplication.sharedApplication().orderedDocuments().firstObject().showMessage')
it' currently at workbench

` xxx.js
import UI from 'sketch/ui';
export function onStartUp(context){
  UI.message('Sketch-plugin-demo 插件已启动');
}
`
`mainfest.json
{
  "identifier": "com.sketchapp.examples.text-utilities",
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "commands": [
    {
      "name": "Actions",
      "identifier": "sketch-plugin-demo.actions",
      "script": "./text-utilities.js",
      "handlers": {
        "run": "onRun",
        "actions": {
          "Startup": "onStartUp",
          "Shutdown": "onShutdown"
        }
      }
    }
  ],
  "menu": {
    "title": "Sketch Plugin",
    "items": ["sketch-plugin-demo.actions"]
  }
}
`

**Comment by mathieudutour** [comment]
This isn't related to skpm, please open an issue on the SketchAPI repo
