### ISSUE TITLE
Small change to plugin reloading in Sketch 45

### ISSUE THREAD

**Issue by bomberstudios** [skpm/skpm#40]
Hi there,

we're about to merge a small refactor in the code that watches the Plugin directory for changes, and as a consequence of that, Sketch will no longer automatically load plugins added externally (i.e: via `skpm link`). It would be nice if `skpm` would warn users about that, and ask them to relaunch Sketch when linking a new plugin.

The [`AlwaysReloadScript` preference](http://developer.sketchapp.com/introduction/preferences/#always-reload-scripts-before-running) will  still work as usual, so the change only affects the linking phase.

**Comment by mathieudutour** [comment]
cool, thanks for the heads up

**Comment by mathieudutour** [comment]
fixed in 0.9.11
