### ISSUE TITLE
Use 'author' key from package.json in manifest.json

### ISSUE THREAD

**Issue by bomberstudios** [skpm/skpm#47]
Currently it seems to be ignored, and needs to be added manually to manifest.json for it to show up in Sketch's plugin list.

**Comment by mathieudutour** [comment]
I think the format of the author field is not the same in package.json and manifest.json: https://docs.npmjs.com/files/package.json#people-fields-author-contributors

Do we need to parse the author field and return only string or a object is fine as well?

**Comment by bomberstudios** [comment]
Ah, you're right… I was assuming 'author' would just include a name, but it's slightly more complex for npm (_of course_).

We don't support an object for 'author' in Sketch, but since we do support an `email` attribute, maybe it makes sense to parse those out of the `package.json` file?

**Comment by mathieudutour** [comment]
fixed in https://github.com/skpm/skpm/commit/602ed09e8c6fd552d0449d43005c72880d1c1266, will publish when #44 is ready

**Comment by bomberstudios** [comment]
Awesome, thanks a lot! : )
