### ISSUE TITLE
Include the Resources folder with "--watch --run" 

### ISSUE THREAD

**Issue by rborn** [skpm/skpm#49]
For the case when we run `skpm build --watch --run` would be good if the plugin could be launched again without actually re-building it.

This is useful for the case the plugin uses either external commands from the assets folder and any change to this command would be run again.

Thank you

**Comment by mathieudutour** [comment]
it's a bit hard to know which command to re-run when an external file change tho

**Comment by mathieudutour** [comment]
thinking a bit more about it and I don't think that's something I want to do, too much magic needed to determine which command to re-run and there are some cases where you actually don't want to re-run when assets change (webview for example).

So I'm closing this. Feel free to re-open if you have some argument that I might have missed
