### ISSUE TITLE
Investigate source maps

### ISSUE THREAD

**Issue by mathieudutour** [skpm/skpm#50]
https://twitter.com/matt_sven/status/883004835225903104

cc @matt-curtis

**Comment by mathieudutour** [comment]
tried `devtool: 'inline-source-map'', doesn't work. The stack trace that we get from sketch looks like `run@[native code]` so it seems hard to do anything

**Comment by matt-curtis** [comment]
You may be able to get better results from Safari > Develop > `Your Computer` (and then guess which context belongs to your plugin.)

**Comment by mathieudutour** [comment]
but the context closes as soon as there is an error, doesn't it?

**Comment by matt-curtis** [comment]
@mathieudutour The context disappears as soon as your plugin finishes running, but you can still use `coscript.shouldKeepAround = true`. You can also tell Safari to automatically open an inspector.
