### ISSUE TITLE
Symlink not showing up in Sketch v45.1

### ISSUE THREAD

**Issue by florianpnn** [skpm/skpm#51]
Hi there,

I'm trying to use the symlink but it seems to be broken in Sketch 45.1.
Here's the error when I try to double click the alias to see if there is a problem:
![screen shot 2017-07-10 at 4 26 30 pm](https://user-images.githubusercontent.com/2725387/28022873-a0be58cc-658c-11e7-9b11-312b528c2087.png)

**Comment by mathieudutour** [comment]
* did you build the plugin?
* Did you rename the plugin?
* Did you change the "main" field in your package.json?

**Comment by florianpnn** [comment]
> did you build the plugin?
Yes

> Did you rename the plugin?
Yes

> Did you change the "main" field in your package.json?
Yes

The plugin is showing up in the list of plugins in `Preferences` but doesn't show up in the menubar under `Plugins`

**Comment by mathieudutour** [comment]
> Did you change the "main" field in your package.json? yes

That's why. Delete the alias in the plugin folder and try to link it again

**Comment by florianpnn** [comment]
I did this a couple of time and it had no effect on the outcome.

**Comment by mathieudutour** [comment]
just to be sure: skpm@0.10.1 ?

**Comment by florianpnn** [comment]
Yep, is there anything I can do to help produce some logs?

**Comment by mathieudutour** [comment]
hum not really, looks like the alias is pointing to the wrong file.

Can you copy paste your package.json? And tell me where the alias is pointing to (right click -> Get Info -> Original)?

**Comment by florianpnn** [comment]
Package.json
```JSON
{
	"name": "sketch-2-react",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1",
		"build": "skpm build",
		"publish": "skpm publish"
	},
	"author": "",
	"license": "ISC",
	"engines": {
		"sketch": ">=3.0"
	},
	"devDependencies": {
		"skpm": "^0.10.1"
	},
	"skpm": {
		"manifest": "src/manifest.json",
		"main": "sketch-2-react.sketchplugin"
	}
}
```

Alias pointing to : `/Users/florianpnn/Documents/projects/sk-plugins/sketch-2-react/sketch-2-react.sketchplugin` (which is accurate)

**Comment by mathieudutour** [comment]
wait so symlink is ok but not the plugin then?

* What happens when you double click on `/Users/florianpnn/Documents/projects/sk-plugins/sketch-2-react/sketch-2-react.sketchplugin`? 
* If you inspect `/Users/florianpnn/Documents/projects/sk-plugins/sketch-2-react/sketch-2-react.sketchplugin` (right click -> show content), is there a `Contents/Sketch/manifest.json`?

**Comment by florianpnn** [comment]
It's a weird bug, when I install the plugin it installs it but don't show up in the `Plugins` dropdown.
It contains all it should, `manifest.json` & `index.js`

**Comment by mathieudutour** [comment]
That's really weird indeed. What does your manifest look like?

**Comment by florianpnn** [comment]
I just tried with the basic boilerplate and it is working, therefore I assume that I messed up somewhere.
I'll investigate and close if I don't see any problem coming from the tool itself.

**Comment by mathieudutour** [comment]
ok, even if it's with your code, keep me updated: if we can warn or something it could be great

**Comment by florianpnn** [comment]
I couldn't find where I screwed up, I c/p the same plugin in a new `skpm init` and it worked.

**Comment by Ruina6** [comment]
I just had the same problem, it was at my manifest.json, i messed up the "identifier" field i change it back to the default "my-command-identifier" and it worked fine again, i hope it helps.

**Comment by mathieudutour** [comment]
you can change the identifier as long as you change it in the "menu" as well
