### ISSUE TITLE
running babel on node_modules

### ISSUE THREAD

**Issue by pcooney10** [skpm/skpm#53]
Hi,

I am working on a `react-sketchapp` project that uses skpm.  One of the node modules I am using has ES.next syntax that isn't getting recognized during compilation (`skpm build --watch --run`):
[the equals sign after `static propTypes`](https://gist.github.com/pcooney10/e2e699549e47284f3eae8aca390c2148#file-index-js-L18).

I have included a .babelrc file at the root of my project with the following settings, per suggestions from [here](https://stackoverflow.com/questions/35345000/equal-sign-in-bad-place-causes-unknown-token-exception) & [here](https://stackoverflow.com/questions/45177215/babel-webpack-settings-for-react-sketchapp-project-with-es2015-es-next): 

    {
      "presets": ["es2015", "react", "stage-0"],
      "plugins": ["transform-runtime", "transform-class-properties"]
    }

Does `skpm` ignore the `node_modules` folder? If so, how can I change that? A full repo where the issue can be reproduced is available [here](https://github.com/pcooney10/rn-calendar).

**Comment by mathieudutour** [comment]
yes it's ignoring the node_modules and I think it's a good default, it's pretty rare to parse the entire node_modules, super slow.

But happy to accept an option to enable it. The interesting line is here: https://github.com/skpm/skpm/blob/master/lib/utils/webpackConfig.js#L46

**Comment by pcooney10** [comment]
Ok, thank you for the quick response @mathieudutour. If I were to use a `webpack.config.js` file instead of a .babelrc file, could I tell it look there with an include statement? Something like `include: /(node_modules\/react-native-calendars)/`?

**Comment by mathieudutour** [comment]
you can pass your own webpack.config.js yes. I think putting
```js
module.exports = {module: {
  rules: [
    BABEL_CONFIG_HERE
  ]
}}
```
should work

**Comment by pcooney10** [comment]
Ok cool, I am trying this but it doesn't seem to recognize jsx in my `/src` directory anymore: 

    module.exports = {
      module: {
        rules: [
          {
            test: /\.jsx$/,
            exclude: /(node_modules)/,
            include: /(node_modules\/react-native-calendars)/,
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['react', 'es2015', 'stage-0'],
                plugins: ['transform-runtime', 'transform-class-properties']
              }
            }
          }
        ]
      }
    };

( I know this is way outside of the scope of the project, but I am very grateful for the help ! )

**Comment by mathieudutour** [comment]
I think `include` makes it look only there. Instead, you should adjust your `exclude` regex: `/node_modules\/(?!(react-native-calendars))/` or something like this
