### ISSUE TITLE
Missing "name" field in the package.json?

### ISSUE THREAD

**Issue by bomberstudios** [skpm/skpm#55]
I'm trying to use the `skpm publish` feature, and I'm getting this error:

`error Missing "name" field in the package.json`

There's definitely a `name` field in `package.json` (I've also tried setting it in `skpm.name` in `package.json`, and in `manifest.json`).

I'm probably doing something wrong, but there's not a lot of documentation on the publish section.

Thanks in advance!

**Comment by bomberstudios** [comment]
Apparently, changing https://github.com/skpm/skpm/blob/master/lib/skpm-publish.js#L55 to

```
var repo = (program.repoUrl && extractRepository((program.repoUrl))) || skpmConfig.repository
```

fixes the issue. I still get an error when publishing, so I'm hesitant to open a PR:

![screen shot 2017-07-24 at 14 34 13](https://user-images.githubusercontent.com/3832/28523543-3ecb82a6-707d-11e7-98ae-1608f68f0440.png)

**Comment by mathieudutour** [comment]
oh waow, not sure what happened here. Yes the two lines should be changed.

What's the error that you get on the last step?

**Comment by bomberstudios** [comment]
The error looks like this:

![screen shot 2017-07-24 at 17 39 16](https://user-images.githubusercontent.com/3832/28531857-584cffbe-7098-11e7-8941-25fceea66042.png)

…

![screen shot 2017-07-24 at 17 39 25](https://user-images.githubusercontent.com/3832/28531864-5c6bdffc-7098-11e7-8ca4-b8d4710ed72b.png)

**Comment by bomberstudios** [comment]
I've opened a PR for the repository issue, not sure what's going on with the other error (it could be related with my crappy connection, I'll investigate a bit more)

**Comment by mathieudutour** [comment]
found it, will fix
