### ISSUE TITLE
cant push the tag

### ISSUE THREAD

**Issue by mcansh** [skpm/skpm#59]
I have yarn and npm set up so they dont use the 'v' prefix on releases and that causes skpm to not be able to push the tag for obvious reasons as it cant find 'v1.0.1'

**Comment by mathieudutour** [comment]
hum wait, `npm version patch` return `v1.0.1` even if the tag is called `1.0.1`?

**Comment by mcansh** [comment]
in `.npmrc` I have `tag-version-prefix=` set so my tags are just `1.0.0` etc. example https://github.com/mcansh/blog/releases/tag/2.4.5, notice the tag is just `2.4.5` and not `v2.4.5`.

**Comment by mcansh** [comment]
for my plugin repo though, I could initiate a local npmrc file which reverses that ¯\_(ツ)_/¯

**Comment by mathieudutour** [comment]
Yes but what I’m doing is getting the output from npm version. There shouldn’t be any issue if non output the right tag. But I guess it doesn’t. Not sure how to solve it, looks like an npm bug

**Comment by mcansh** [comment]
¯\_(ツ)_/¯ seems to have solved itself
