### ISSUE TITLE
'@skpm/file-loader' is not in the npm registry.

### ISSUE THREAD

**Issue by javascriptDev** [skpm/skpm#64]
'@skpm/file-loader' is not in the npm registry'. when i am type npm i -g skpm

**Comment by mathieudutour** [comment]
what version of npm are you using? because it's definitely in the registry: https://www.npmjs.com/package/@skpm/file-loader

**Comment by michaeldick** [comment]
Same problem

**Comment by mathieudutour** [comment]
same question

**Comment by michaeldick** [comment]
Version `3.10.9`, could it be because my company has their own private npm under `@sm`?

**Comment by mathieudutour** [comment]
hum not sure. What shows up with `npm search skpm`?

**Comment by michaeldick** [comment]
![image](https://user-images.githubusercontent.com/100761/29892926-3c5f8e52-8d85-11e7-9b40-10a6d26314af.png)

PS: Thanks for your help!

**Comment by michaeldick** [comment]
I wonder if it could be because of my companies network set up ... VPN's, etc? I've had issues in the past because of it.

**Comment by mathieudutour** [comment]
hum possibly, definitely an npm issue, can't do much about it :/

**Comment by mathieudutour** [comment]
maybe update to the latest npm version

**Comment by michaeldick** [comment]
Cool, thanks for the help! I'll try on my personal machine at home. Cheers!

**Comment by michaeldick** [comment]
PS: I skipped installing the cli globally and installed it as a devDependency into my project instead – worked just fine 👍 

Now I'm off to coding plugins <3

**Comment by mathieudutour** [comment]
oh weird, so it's not working when installing globally but working when installing as a dependency?

**Comment by michaeldick** [comment]
Investigating more ... the cli tools are working just fine. So, it's possible skpm installed even though it was failing on `file-loader` earlier...

**Comment by mathieudutour** [comment]
I'm closing this since it's a npm bug and I don't really have any actionable here
