### ISSUE TITLE
How to go from code that runs as cocoascript to JS for this

### ISSUE THREAD

**Issue by sdaitzman** [skpm/skpm#68]
For example, how would I transfer `[fill setColor:[MSImmutableColor colorWithSVGString: colors[r]]];` to the proper JS that SKPM can transpile? I haven't worked with Objective-C for years if that makes a difference.

**Comment by mathieudutour** [comment]
something like `file.setColor(MSImmutableColor.colorWithSVGString(colors[r]))`
