### ISSUE TITLE
issue importing npm packages

### ISSUE THREAD

**Issue by lifeiscontent** [skpm/skpm#70]
when running the following code and trying to run skpm build I get the following error:

code:
``` js
import emmet from 'emmet';
import 'emmet/bundles/snippets';
import 'emmet/bundles/caniuse';

export default emmet;

```

error:
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

any help would be appreciated here. Thanks!

**Comment by mathieudutour** [comment]
your code doesn't look like a sketch plugin. Where exactly to you put it?

**Comment by lifeiscontent** [comment]
@mathieudutour you can see the code here: the lines I’ve commented out don’t compile properly:

https://github.com/lifeiscontent/emmet-sketch/blob/master/src/script.js

**Comment by mathieudutour** [comment]
hum I'm guessing emmet using some dynamic require and that doesn't work well with webpack. Is emmet compatible with webpack?

**Comment by lifeiscontent** [comment]
Yes, I’ve tried it outside of skpm and it seems to compile.

**Comment by mathieudutour** [comment]
I just tried your code and it compiles just fine: it's a warning, not an error
