### ISSUE TITLE
Adding 'plugins' to user-defined webpack config produces incorrect build output for commands

### ISSUE THREAD

**Issue by romansp** [skpm/skpm#73]
Looking through `skpm` sources I figured out that I can use my own `webpack.config.js` to augment included skpm's webpack config.

I was playing around this feature and stumbled upon pretty weird case when I add custom `plugins` into webpack config.

Though build finishes successfully and my plugins are applied, output command scripts appear wrapped multiple times into `run` function (by `WebpackHeaderFooterPlugin`), moreover commands from different "script" are included (I have multiple "script"s defined in "manifest.json"). If you try to run it from Sketch, it will crash with an exception: `Exception: TypeError: undefined is not an object (evaluating that.context = context)`. 

I guess that's caused by the following in `webpackConfig.js`:
https://github.com/skpm/skpm/blob/791429d0965f76a4c20cdf7ce15625c1efb803e5/lib/utils/webpackConfig.js#L166

My guess is that when multiple "script" files are run through 'webpack' `userDefinedWebpackConfig.plugins` becomes mutated.

Changing it to `let plugins = [...userDefinedWebpackConfig.plugins] || []` did indeed fixed that.

I can provide a PR that introduces exactly that change, or can provide with repro case for you to look around.

**Comment by mathieudutour** [comment]
oh yes, of course, silly me.

I'd love a PR yes, can you make sure it's compatible with node 6 (don't remember when `[...]` was introduced)?

**Comment by romansp** [comment]
@mathieudutour , while we are here, what do you think of similar support for webpack's `module.rules` or maybe even more stuff? 

I'm currently using typescript and vue.js for Sketch plugin development and can't use `skpm`'s preconfigured `staticResourceLoader` and `babelLoader`, as I'm overriding those completely with my own `rules` for loaders.

That's shouldn't be very hard to implement. Can do it in my spare time, if you find it useful.

**Comment by mathieudutour** [comment]
I'm all for more support of custom webpack config. I was just a bit concerned that if I added to skpm rules to the custom rules, there would be some conflicts and that would be really hard to debug and understand for the user

**Comment by mathieudutour** [comment]
Thinking a bit more about the webpack config: what do you think about having a special file `webpack.config.skpm.js` which should expose a function taking the default config as an argument? The user can do whatever they want with it and it's clear that if something breaks, it's their config so it's easier to debug and fix. (that's what preact is doing: https://github.com/developit/preact-cli#webpack)

**Comment by romansp** [comment]
That sounds good. I like it.

Want to share my current experience. At first, I was happily surprised that I can add `webpack.config.js` or `.babelrc` and it will go right into the `skpm build` process, so I can easily add support for typescript, vue, whatever. After I added rules and tried building I was pretty much confused of where did skpm rules go and why babel stopped doing its thing. It wasn't clear at all.

So, yeah I definitely like that approach more than the current. I'm also starting to think about dev/prod builds: tree shaking, minification, etc. With the approach of having a special file it will be easier to setup dev/prod builds, I guess at least.

I saw your comment mentioning that `skpm` is in the finished state and it definitely is, so I'm not quite sure if you are in the mood to implement new features. I like working with it anyway, but giving some additional knobs will be a huge :+1: to `skpm`.

**Comment by mathieudutour** [comment]
I'm actually completely re-writing it to split the build process from everything because I don't want to bloat plugin with unnecessary stuff 😄 
I'll see if I can integrate that during the rewrite

**Comment by mathieudutour** [comment]
I'd love it if you could check out the new readmes before I merge 😄 
https://github.com/skpm/skpm/blob/9c57129bd8e21ad9692e11611617db1920185dde/README.md
https://github.com/skpm/skpm/blob/9c57129bd8e21ad9692e11611617db1920185dde/template/README.md

**Comment by romansp** [comment]
Woaw, that was quick. Just looked through and it looks good to me. Also templating support is really cool stuff 👍.

**Comment by mathieudutour** [comment]
If you are up to create a template for typescript, i’d happily linked to it :)

**Comment by romansp** [comment]
I would really like to do it. However my current setup is far from ideal, and I need to integrate recent changes to `skpm` first. Anyway, will try to find some time to contribute back :)

**Comment by romansp** [comment]
Just pushed template for `skpm` with TypeScript and TSLint here: https://github.com/romansp/skpm-typescript. 
That was really easy to do. Thanks a lot for your efforts adding support for custom templates and `skpm` in general. 👍

**Comment by mathieudutour** [comment]
awesome! Do you think we could generate the `sketch.d.ts` from the class dump? 🤔

**Comment by romansp** [comment]
I was thinking about generation of `sketch.d.ts` automatically and maybe starting it as a next pet-project. Unfortunately, I'm out of ideas from where do I even start. If you have some thoughts I will be happy to discuss this.

For Sketch plugin that's currently in development I manually fill `sketch.d.ts` using class-dump as a reference. I also have `globals.d.ts` where I put things relevant to `NS*` and Mocha. But decided to keep template clean and didn't include it.

I already benefited a lot from doing types both for refactoring and overall development purposes. Of course it requires initial efforts, but I don't regret at all.

**Comment by mathieudutour** [comment]
it should be possible to parse a header file (something similar to this: https://github.com/subh007/ObjCParser) and then generate a types file from that object. A first step could be just getting the methods without the types of the arguments.

Probably won't have time to look into it just right now but maybe in a couple of weeks

**Comment by romansp** [comment]
Thanks for the link, that's the approach I'm thinking of. Will look into this particular tool (or maybe other alternatives) in my spare time. Will keep you updated, if there will be any progress 😄 .

**Comment by mathieudutour** [comment]
We've got the headers parsed here https://github.com/skpm/sketch-headers if you want to use them to generate a typescript types file

**Comment by romansp** [comment]
Oh my, that's impressive! Great starting point for typescript generation. Will definitely use it. Thank you!

**Comment by chpio** [comment]
> Nov 11, 2017

i guess there's noone wanting to write sketch plugins in TS?
