### ISSUE TITLE
UnhandledPromiseRejectionWarning when building

### ISSUE THREAD

**Issue by aparajita** [skpm/skpm#79]
I'm getting this when building with node 8.7.0:

>(node:68828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: c.close is not a function
>(node:68828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mathieudutour** [comment]
what version of `@skpm/builder` are you using? I release a new version yesterday that should fix this

**Comment by aparajita** [comment]
La dernière version, 0.1.3. Pourquoi skpm-builder n'est pas dans un repo distinct?

**Comment by mathieudutour** [comment]
should be fixed in 0.1.4.

Because it's a lot more convenient to have them all in the same repo since I often need to change them all at the same time

**Comment by aparajita** [comment]
Compris. Thanks for all of your work!
