### ISSUE TITLE
skpm/file-loader corrupts output files

### ISSUE THREAD

**Issue by romansp** [skpm/skpm#80]
It's not actually `@skpm/file-loader`'s fault, but `file-loader`'s. 

See: 
* https://github.com/webpack/webpack/issues/5745
* https://github.com/webpack-contrib/file-loader/pull/183

Can you integrate upstream changes into the fork, at least up until v1.1.2 of `file-loader`? Thanks.

I guess, I can open PR straight into @skpm/file-loader?

**Comment by mathieudutour** [comment]
That'd be awesome 👍

**Comment by mathieudutour** [comment]
I merged the upstream changes

**Comment by romansp** [comment]
Awesome. Many thanks! Just tried and it works as intended. 👍
