### ISSUE TITLE
How to handle npm modules which include es6?

### ISSUE THREAD

**Issue by romansp** [skpm/skpm#82]
I wonder what's the appropriate way to configure skpm in a way, so ES6 in `/node_modules/` will be transpiled to ES5 by babel.

Right now I'm trying to use `sketch-polyfill-fetch` (inside Mocha context), but I got the following exception
`SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode..`
And after that `cocoascript-class` also uses `const` declarations.

Of course, I can mutate webpack via `webpack.skpm.config.js` and update "exclude" options, but I feel like I'm doing something wrong here.

**Comment by romansp** [comment]
Okay, that's possibly due to issue described in https://github.com/skpm/sketch-polyfill-fetch/issues/6, as I'm also on El Capitan, and `Promise` is also not available.

Anyway, the question remains open.

**Comment by mathieudutour** [comment]
yeah that's the issue. It's a bit more complex in the case of the fetch polyfill because of Mocha things.

For your original question, you can add a custom `.babelrc` in your project not to ignore the noce_modules
