### ISSUE TITLE
Proposal to add skpm plugins

### ISSUE THREAD

**Issue by aparajita** [skpm/skpm#83]
Hi Mathieu,

I want to add a template to skpm based an improved version of [NibUI](https://github.com/aparajita/Sketch-NibUITemplatePlugin). An essential part of making the template work is a task that exports the xib to a nib and also writes out connection info into a file.

Since this task should logically be part of the skpm watch process, I propose to add a simple plugin interface to skpm/skpm-build that would allow templates to provide hooks into the various lifecycle points, e.g.:

- create
- build
- link
- watch
- publish

What do you think? It's something I'm willing to work on.

**Comment by aparajita** [comment]
You mean what would the file structure be? Like the [standard template](https://github.com/skpm/skpm/tree/master/template) but at the top level there would be an skpm-plugin.js file which skpm would look for when instantiating the template.

There are a couple of ways that the plugin can register with skpm. Perhaps the simplest would be for the plugin to export a register function:

```js
exports.register = function(skpm) {
  return {
    hooks: {
      create: createFunc,
      build: buildFunc,
      link: linkFunc,
      watch: watchFunc,
      publish: publishFunc
   },
   options: {
    // reserved for future options
   }
 }
```

Only the hooks that are actually defined in the plugin need to be exported and of course `options` can be skipped if there are no options. The `skpm` parameter would give the plugin access to an skpm API. Not sure what that would be right now, but I'm sure it will come in handy at some point.

**Comment by mathieudutour** [comment]
I see. I have the feeling that this could just be done with webpack plugins and npm scripts (`prebuild`, `prepublish`, etc.) but maybe it's a nicer way to encapsulate that?

I just don't want it to be something unmaintainable and would prefer to delegate as much as possible to webpack and npm if possible.

Like your example about nibUI is def possible with webpack plugins. Do you have some example that wouldn't be?

**Comment by aparajita** [comment]
I hadn't thought of using webpack plugins, I suppose it could be done that way. I'm not looking forward to deciphering the webpack documentation.
