### ISSUE TITLE
TypeError: exports[key] is not a function, when using handler actions

### ISSUE THREAD

**Issue by bryanberger** [skpm/skpm#84]
*manifest.json*
```
{
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "commands": [
    {
      "name": "my-command",
      "identifier": "my-command-identifier",
      "script": "./my-command.js",
      "handlers": {
          "actions": {
              "ArtboardChanged.finish": "ArtboardChanged"
	  }
       }
    }
  ],
  "menu": {
    "isRoot": true,
    "items": [
      "my-command-identifier"
    ]
  }
}
```

*my-command.js*
```
export default function(context) {
  context.document.showMessage("It's alive 🙌")
}

export function ArtboardChanged(context) {
  console.log("ArtboardChanged")
}
```

*error*
```
TypeError: exports[key] is not a function. (In 'exports[key](context)', 'exports[key]' is undefined)
line: 487
stack: run
column: 17
```

Webpacked output is showing the functions properly:
```
that['ArtboardChanged'] = run.bind(this, 'ArtboardChanged');
that['onRun'] = run.bind(this, 'default')
```

Seems to be related to: https://github.com/skpm/skpm/blob/8731f82c2f2b748b79f5fc8e4440499d57b297c3/skpm-builder/src/utils/webpackConfig.js#L16

When `key` isn't a function, but is instead this object:
```
{
    api = "<MOJavaScriptObject: 0x604000a37b60>";
    command = "<MSPluginCommand: 0x600000eee280>";
    document = "<MSDocument: 0x7fdb5b9063f0>";
    plugin = "<MSPluginBundle: 0x6000000fd000>";
    scriptPath = "/Users/bb/dev/test-plugin/plugin.sketchplugin/Contents/Sketch/my-command.js";
    scriptURL = "file:///Users/bb/dev/test-plugin/plugin.sketchplugin/Contents/Sketch/my-command.js";
    selection =     (
    );
}
```

Could replace L16 with an additional function type check
```
if (key === 'default' && typeof exports === 'function') {
    exports(context);
} else if(typeof exports[key] === 'function') {
    exports[key](context);
}
```

The plugin works fine, but the error is produced after running `npm start` and after each save (on watch) Any idea about that object being passed in?

**Comment by mathieudutour** [comment]
hum yeah I need to clean that up. I'm not sure I tested `npm start` with named exports, might be the culprit

**Comment by mathieudutour** [comment]
oh waow, that's actually super interesting, and a bug in Sketch:
- when you don't specify "handlers", the default handler is `onRun`
- when you specify "handlers" (like here), the default handler become `run`

Turns out I'm defining a function called `run` so it gets called and crashed because an argument is missing.

(btw, I don't think you want to use `npm run start` when using actions, it will run your handler on every same (hence the error). Use `npm run build` instead)

**Comment by richardpenner** [comment]
I'm seeing this same error. I have a working plugin but am trying to adopt this toolchain. I've removed almost everything but can't get around this. 
Manifest.json:
```
{
  "compatibleVersion": 3,
  "bundleVersion": 1,
  "commands": [
    {
      "name": "Settings 4",
      "identifier" : "show-settings",
      "script": "./dialog.cocoascript"
    }
  ],
  "menu": {
    "title": "Figure-1-Sketch",
    "items": [
      "show-settings"
    ]
  }
}
```
dialog.cocoascript:
```
export default function(context){
    log("hi mom!");
}
```
Any ideas?

**Comment by mathieudutour** [comment]
use `.js` and not `.cocoascript`.

**Comment by richardpenner** [comment]
OK, just one more thought: `skpm` is promoted on developer.sketchapp.com, where cocoascript examples abound. You may want to make it clearer that cocoascript is not supported – in my case it would've saved a lot of time.

**Comment by mathieudutour** [comment]
yes I need to change the examples

**Comment by mateus** [comment]
I'm having the same issue. So what's the proper way to have a script with handlers?

```
// plugin.js
export default function (context) {
  ...
}

export function onSelectionChanged(context) {
  ...
}
```

```
// manifest.json
...

"script" : "plugin.js",
"handlers": {
  "actions" : {
      "SelectionChanged.finish" : "onSelectionChanged"
    }
}
```

This code is certainly not right.

**Comment by mathieudutour** [comment]
yes you need to define the handler:
```
"handlers": {
  "run": "default",
  "actions" : {
      "SelectionChanged.finish" : "onSelectionChanged"
    }
}
```

but honestly, I would use another file. If you use the same file, you might end up being confused about the context it's being run into, etc..

**Comment by mateus** [comment]
This also does not seam to work:

```
// manifest.js

    "script" : "plugin.js",
      "handlers": {
        "run": "default",
        "actions": {
          "SelectionChanged.finish" : "onSelectionChanged"
        }
      }
```

```
// plugin.js

import { createWebview } from './helpers';

export default function (context) {
  createWebview(context, {}, 'Polaris');
}

export function onSelectionChanged(context) {
  // Do Something
}
```

I should be doing something incorrect here. What would be the right way to do it using another file as you suggested?

**Comment by mathieudutour** [comment]
```
"commands": [
    {
      "name": "onSelection",
      "identifier": "my-command-identifier.selection",
      "handlers": {
        "actions": {
          "SelectionChanged.finish" : "onSelectionChanged"
        }
      },
      "script": "./on-selection.js"
    },
    {
      "name": "my-command",
      "identifier": "my-command-identifier.normal-command",
      "script": "./plugin.js"
    }
  ],
```

**Comment by mateus** [comment]
Using these commands who should the `on-selection.js` look like then?

Also, by not including the key `run` inside `handlers` I get this error:
```
Error in command onSelection Script at path project/plugin.sketchplugin/Contents/Sketch/on-selection.js does not contain a handler function named: run.
```

**Comment by mathieudutour** [comment]
well your `on-selection.js` should look like this:
```
export function onSelectionChanged(context) {
  // Do Something
}
```

**Comment by mateus** [comment]
Yeah. My configuration looks exactly what you are suggesting but I still can't get it to work. 

```
"commands": [
    {
      "name": "onSelection",
      "identifier": "my-command-identifier.selection",
      "handlers": {
        "actions": {
          "SelectionChanged.finish" : "onSelectionChanged"
        }
      },
      "script": "./selection-changed.js"
    },
    {
      "name": "search",
      "identifier": "my-command-identifier.normal-command",
      "script": "./plugin.js"
    }
  ],
```

```
// plugin.js
import createWebview from './utils/webview';

export default function(context) {
  createWebview(context, {}, 'Title');
}
```

```
// selection-changed.js

export function onSelectionChanged(context) {
  context.document.showMessage("It's changed");
}
```

I'm still getting that error about not having `run`.

```
Error in command onSelection Script at path /Users/mateus/Documents/project/plugin.sketchplugin/Contents/Sketch/selection-changed.js does not contain a handler function named: run
```

**Comment by mathieudutour** [comment]
when does the error happen? when you select an layer?

**Comment by mateus** [comment]
I see it on the `sketch-dev-tools` logs and also on the terminal after run `npm run start`.

**Comment by mathieudutour** [comment]
`npm run start` will try to run each command after each build and the selection command can't run by itself.

Use `npm run watch` to just build the command

**Comment by mateus** [comment]
Yeah, took me some time to figure this out. Sorry I didn't mention it here. Thanks @kohaXun
