### ISSUE TITLE
Sketch version below 43 will cause webpack plugins undefined

### ISSUE THREAD

**Issue by xiaoping0x** [skpm/skpm#86]
https://github.com/skpm/skpm/blob/b28241db9c978e5173b80de65cf69b7ac682d312/skpm-builder/src/utils/webpackCommandPlugin/index.js#L9

Should check result here

https://github.com/skpm/skpm/blob/b28241db9c978e5173b80de65cf69b7ac682d312/skpm-builder/src/utils/webpackConfig.js#L142

**Comment by mathieudutour** [comment]
I'm not sure I understand. How does the sketch version influence how the plugins are built?

**Comment by xiaoping0x** [comment]
The problem is that when my sketch is below version 43, webpackCommandPlugin will return `[undefined]` which will cause webpack error.
