### ISSUE TITLE
Resource path mangling makes it difficult to add icons for Sketch Runner

### ISSUE THREAD

**Issue by romannurik** [skpm/skpm#87]
skpm currently bundles PNG resources in a weird way, renaming something like `my_icon.png` to  `Resources/_webpack_resources/7dcd272300c943fdb6d93511b04e5e41.png`. This makes it hard to provide [icons for Sketch Runner](http://sketchrunner.com/developers.html), since you need to put the final path to the PNG asset in your manifest JSON, e.g.:

```
{
  "identifier" : "my-command",
  "icon" : "icons/my_icon.png",
}
```

It'd be great if there was either:

a. an option to avoid renaming resources (e.g. by looking for name patterns like `my_icon.norename.png` or something)

b. a way for skpm to automatically rewrite PNG paths in the manifest to their final name, e.g.:

```
{
  "identifier" : "my-command",
  "icon" : "_webpack_resources/7dcd272300c943fdb6d93511b04e5e41.png",
}
```

**Comment by mathieudutour** [comment]
I'm usually just putting them in the `Resources` folder directly and making sure that git ignore the right things (see skpm/sketch-debugger).

But yes, we talked about it here: https://github.com/skpm/skpm/issues/45#issuecomment-340915993

**Comment by romannurik** [comment]
Ah, that's a good point. I tend to avoid mixing source material w/ output material so would probably avoid keeping .png sources inside the `.sketchplugin` directory, but that's just me. My current workaround is actually just to copy the files as a post-skpm build step:

*package.json*
```
"scripts": {
    "build": "skpm-build && mkdir -p foo.sketchplugin/Contents/Resources && cp -rf icons/*.png foo.sketchplugin/Contents/Resources",
...
```

Would love a more formal solution at some point though :)

**Comment by aparajita** [comment]
@romannurik It's very easy to do what you want with copy-webpack-plugin.

I put all of the static resources I want to copy straight into the plugin Resources in a `resources` folder next to `src`. Then I use this code in `webpack.skpm.config.js`:

```javascript
'use strict'

const CopyWebpackPlugin = require('copy-webpack-plugin')
const merge = require('lodash.merge')
const { skpm } = require('./package.json')

const pluginResourcesPath = `${skpm.main}/Contents/Resources`

const webpackConfig = {
  plugins: [
    new CopyWebpackPlugin([
      {
        from: path.resolve('./resources'),
        to: path.resolve(pluginResourcesPath)
      }
    ])
  ]
}

module.exports = function (config, isPluginCommand) {
  if (isPluginCommand) {
    merge(config, webpackConfig)
  }
}
```

I use `lodash.merge` to ensure I'm not messing up any of the original config.

**Comment by AMoreaux** [comment]
Thx @aparajita . You can remove lodash since you use es6.

```
'use strict'

const CopyWebpackPlugin = require('copy-webpack-plugin')
const path = require('path')
const { skpm } = require('./package.json')

const pluginResourcesPath = `${skpm.main}/Contents/Resources`

const webpackConfig = {
  plugins: [
    new CopyWebpackPlugin([
      {
        from: path.resolve('./resources'),
        to: path.resolve(pluginResourcesPath)
      }
    ])
  ]
}

module.exports = function (config, isPluginCommand) {
  if (isPluginCommand) {
    Object.assign(config, webpackConfig)
  }
}
```
