### ISSUE TITLE
Problem with compiling cocoa syntax

### ISSUE THREAD

**Issue by oxyberg** [skpm/skpm#88]
Hi. I have used cocoa syntax (`@import` and `[x y]`) in my plugin's code, but skpm generates warnings while compiling plugin.
```
error Error while building ./commands/validate.js
./src/commands/validate.js
Module build failed: SyntaxError: Unexpected token, expected , (25:27)

  23 |  if (errors.length > 0) {
  24 |          var description = errors.join('\n');
> 25 |          var app = [NSApplication sharedApplication];
     |                                   ^
  26 |          [app displayDialog:description withTitle:'TV Scalator found some bad layers'];
  27 |  }
  28 | }
```
What I need to do to enable cocoa syntax?

**Comment by oxyberg** [comment]
I have found issue #22, but it's unclear how to translate cocoa to pure js.

**Comment by mathieudutour** [comment]
yeah the cocoa syntax is a bad idea and should have never be created in the first place haha. 

I wrote a bit about how to transform obj-c syntax into js: http://developer.sketchapp.com/guides/cocoascript/

basically:
* All colons are converted to underscores (the latest underscore is optional).
* Each component of the selector is concatenated into a single string with no separation.
