### ISSUE TITLE
Can't publish: 404 not found

### ISSUE THREAD

**Issue by dploeger** [skpm/skpm#89]
When using skpm publish, it stops just after creating the version tag:

```
⠼ Creating a draft release on GitHub
Error: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#create-a-release",
  "request": {
    "method": "POST",
    "url": "https://api.github.com/repos/dploeger/sketch-plugin-units/releases",
    "headers": {
      "Accept": "application/vnd.github.v3+json",
      "Authorization": "Token **********",
      "User-Agent": "SKPM-Release-Agent"
    },
    "json": {
      "tag_name": "v1.0.0",
      "name": "v1.0.0",
      "draft": true
    }
  }
}
```

I'm not quite sure, why the 404 happens. The URLs used and the tag name is available at the time...

**Comment by mathieudutour** [comment]
Are you sure that the token that you gave to skpm has the right to access the repo?

**Comment by dploeger** [comment]
Yes, as it has already created the tag. It's failing on creating the release. Do I need to set any specific permission in the token? I only created it and checked no further option.

**Comment by mathieudutour** [comment]
the tag doesn't require the token, it's created locally (`git tag`). the token needs the `public_repo` right at least

**Comment by dploeger** [comment]
Ah, I will check that and get back to you. Thanks.

**Comment by dploeger** [comment]
Yes, I guess, that was it. public_repo was unchecked. Could you please update your documentation to reflect that? Sketch developer documentation and skpm are a bit scattered and confusing (the best documentation was actually your README.md in this context, but the Sketch developer documentation sadly doesn't refer to that...)

**Comment by mathieudutour** [comment]
I added some info about it, hopefully it will be useful: https://github.com/skpm/skpm/commit/11c1f8a030e67a0b4c8549f8ea2c86940ae8b038
