### ISSUE TITLE
skpm install failed

### ISSUE THREAD

**Issue by zhixunqiu** [skpm/skpm#90]
skpm/node_modules/keytar/node_modules/.bin:/usr/local/lib/node_modules/skpm/node_modules/.bin:/usr/local/lib/node_modules/.bin:/Users/didi/CRClientTools/arcanist/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
6446 verbose lifecycle keytar@4.0.5~install: CWD: /usr/local/lib/node_modules/skpm/node_modules/keytar
6447 silly lifecycle keytar@4.0.5~install: Args: [ '-c', 'node-gyp rebuild' ]
6448 silly lifecycle keytar@4.0.5~install: Returned: code: 134  signal: null
6449 info lifecycle keytar@4.0.5~install: Failed to exec install script
6450 verbose unlock done using /Users/didi/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
6451 verbose stack Error: keytar@4.0.5 install: `node-gyp rebuild`
6451 verbose stack Exit status 134
6451 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
6451 verbose stack     at emitTwo (events.js:106:13)
6451 verbose stack     at EventEmitter.emit (events.js:191:7)
6451 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
6451 verbose stack     at emitTwo (events.js:106:13)
6451 verbose stack     at ChildProcess.emit (events.js:191:7)
6451 verbose stack     at maybeClose (internal/child_process.js:877:16)
6451 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
6452 verbose pkgid keytar@4.0.5
6453 verbose cwd /Users/didi
6454 verbose Darwin 17.0.0
6455 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "skpm"
6456 verbose node v6.9.1
6457 verbose npm  v5.5.1
6458 error code ELIFECYCLE
6459 error errno 134
6460 error keytar@4.0.5 install: `node-gyp rebuild`
6460 error Exit status 134
6461 error Failed at the keytar@4.0.5 install script.
6461 error This is probably not a problem with npm. There is likely additional logging output above.
6463 verbose exit [ 134, true ]

**Comment by zhixunqiu** [comment]
I install skpm failed,it report upon errors,i don't know how to resolve!

**Comment by mathieudutour** [comment]
hum what version of node are you using? It's an issue about keytar if that helps

**Comment by zhixunqiu** [comment]
node version is v6.9.1,npm version is 5.5.1,Thank you!

**Comment by danielwi** [comment]
Have same problem :( Node v: 8.9.0 NPM v: 5.5.1

**Comment by hi-zhaolei** [comment]
![image](https://user-images.githubusercontent.com/5736062/33761846-759f056c-dc45-11e7-940a-644239193246.png)

install failed. above image is the npm error report.

Runtime: node -v9.2.0 npm -v5.5.1

Anyone can help? THKS

**Comment by nichenqin** [comment]
Same problem, node verion: v8.9.0
The issue happens after I upgraded my mac os system to High Sierra 10.13.2

**Comment by pixelcommerce** [comment]
You have to always make sure that x-code is installed and command line tools are enabled. I found that after installing, skpm installed properly.

**Comment by mathieudutour** [comment]
Oh good catch. @zhixunqiu @nichenqin @danielwi can you make sure you have a command line tools installed (http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/)?

If it works afterwards, I'll add a not in the readme about it

**Comment by nichenqin** [comment]
@mathieudutour It works for me! But there is still error when I tried to install through `npm`, I successfully installed it through `yarn`

**Comment by mathieudutour** [comment]
Cool, I added a note in the readme
