### ISSUE TITLE
Missing "skpm.main" fields in the package.json

### ISSUE THREAD

**Issue by varya** [skpm/skpm#91]
Is it somehow possible to set up the plugin destination not as "main" of package.json? I'm trying to run `skpm` in the repository which already needs "main" field of other purposes. Can I somehow tune `skpm` to look for the value in another field?

```
> skpm build --watch --run

error Missing "skpm.main" fields in the package.json. Should point to the ".sketchplugin" file
```

**Comment by mathieudutour** [comment]
yes you can use
```
"skpm": {
  "main": ...
}
```

Hence the "Missing "skpm.main" fields" ;)
