### ISSUE TITLE
Create window with html page from url

### ISSUE THREAD

**Issue by fxmontigny** [skpm/skpm#92]
Hi, 

I would like to create a window that's opened with a URL.
My goal is to have a login page in my server and create an "iframe" inside Sketch to login or view an account profile.

I have absolutely no idea what is the right way.
I tried this (http://developer.sketchapp.com/reference/api/class/api/Layer.js~Layer.html)
```
context.api().layer <= but layer don't have url setting :'(
```

Do you have any idea? 
:) <3

**Comment by mathieudutour** [comment]
why would a layer have an url?

you might want to look at https://github.com/skpm/sketch-module-web-view
