### ISSUE TITLE
is there anyway can auto reload plugins ?

### ISSUE THREAD

**Issue by nikogu** [skpm/skpm#95]
skpm is a nice tool !

But `npm run watch` can only rebuild the plugins, the Sketch has also read the old cache ?

i try use `always reload scripts before running` (http://developer.sketchapp.com/guides/preferences/) but does not work.

When i develop plugins, i relaunch plugin every time, it's so tired, is is there anyway can auto reload plugins ?

**Comment by mathieudutour** [comment]
it shouldn't cache the plugin if you use `always reload scripts before running`.

Are you perhaps using a long-running script (with `shouldKeepAround`?)

**Comment by nikogu** [comment]
! ! ! thanks a lot, it is `shouldKeepAround` indeed.

i add this for asynchronous, i need find a another way, thanks

**Comment by nikogu** [comment]
https://github.com/skpm/sketch-module-web-view/blob/41e8cc4bee44134aa4a7bc96fb894ecd5eb52c2b/lib/index.js#L126

https://github.com/skpm/sketch-dev-tools/blob/master/src/show-debugger.js#L38

so, if i use webview too, i can not reload plugins success ?
