### ISSUE TITLE
skpm publish does not set a description key when opening a PR to plugin-directory

### ISSUE THREAD

**Issue by bomberstudios** [skpm/skpm#96]
By default, the `add` script in plugin-directory uses the GitHub repo description, but I guess that using the description field in package.json or manifest.json if they are present makes more sense.

Plugins without a description are not valid and won't be published on https://sketchapp.com/extensions/plugins/ so I guess it makes sense to fix this : )

**Comment by bomberstudios** [comment]
While we're at it: it should also clean up the `title` key, and make sure the `author` key shows the actual name of the author, and not its GitHub handle.

**Comment by mathieudutour** [comment]
fixed in v1.0.11
