### ISSUE TITLE
Sketch Runner and Sketch Packs integration

### ISSUE THREAD

**Issue by bryanberger** [skpm/skpm#97]
Do you recommend a workflow for allowing `Sketch Runner` and `Sketch Packs` to pick up the latest built release from skpm?

These 2 awesome tools/platforms require the `.sketchplugin` to live within the repo. By default skpm adds build artifacts to be ignored in `.gitignore`. Removing it from gitignore creates a few issues with the publish command, mostly that the working directory isn't clean when you go to publish.

Any plans to support platforms like this and/or an interim approach (aside from an extra commit)?

**Comment by mathieudutour** [comment]
I’d say that it’s a “won’t fix”. Putting build files in a git repo is pretty bad. 

The fix for sketch runner and sketchpack is pretty simple: look at the appcast.xml (there is a link to it in the plugin-registry), parse it, look at the latest download url. It’s removing a lot of assumptions.

**Comment by bryanberger** [comment]
That’s what I figured. Thanks @mathieudutour

**Comment by mathieudutour** [comment]
I've pinged the runner team, they will look into it :+1:
