### ISSUE TITLE
Support npm install registry option

### ISSUE THREAD

**Issue by sskyy** [skpm/skpm#98]
Hi, I find skpm install command is actually running npm install. Would you please add an option to support specifying npm registry like:

```
skpm create my-plugin --dep-registry=http://xxxx
```
npm install is really slow in some country and many company and school have build their own npm mirror, so with this option the installation can be much faster. 
Thank you for this amazing tool!

**Comment by mathieudutour** [comment]
It doesn’t respect your npm config?

**Comment by sskyy** [comment]
I got it, I should create the project and change registry in package.json and then install. Thank you!
